### ISSUE TITLE
Getting NoMethodError Exception: undefined method `to_sym' when calling API client and using wasabi 3.6.1, savon 2.11.1

### ISSUE THREAD

**Issue by Leo137** [savonrb/savon#1003]
# Bug report

**Current behavior:**

Upon sending an client call to a method that needs arguments, i get the following error:
*** NoMethodError Exception: undefined method `to_sym' for {"getToken"=>{"pszXml"=>["xsd", "string"]}}:Hash

However, if i go back to wasabi 3.5.0, client call works normally.

**Steps to reproduce current behavior:**

* Use savon 2.11.1
* Use wasabi 3.6.1
* Make a Savon client call to a method that uses arguments (ie: client.call(:authenticate, message: { username: "luke", password: "secret" }) )

**Expected behavior:**

Client call should not throw undefined method `to_sym' exception.

**System information:**

* ruby version: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux-musl]
* savon version: 2.11.1

**Comment by pcai** [comment]
Hi - can you provide a stacktrace? Does this issue reproduce in the latest versions of savon and wasabi?

The diff for 3.5 to 3.6.1 is not that big (its mostly test files that changed) so any additional detail you can provide will be helpful: https://github.com/savonrb/wasabi/compare/v3.5.0...v3.6.1

**Comment by pcai** [comment]
please reopen when you have more information
