### ISSUE TITLE
SOAP Header with Custom Namespace sends invalid SOAP

### ISSUE THREAD

**Issue by subdigital** [savonrb/savon#120]
Trying to figure out what the issue is here, but I believe it's something Savon is doing wrong.  I'd be happy to contribute a solution if I can figure out exactly what's wrong.

_(Using the "eight" branch in my Gemfile)_

The service I'm consuming expects a custom SOAP header element like this:

```
<head:Header>
   <head:Username />
   <head:Password />
   <head:Application />
</head:Header>
```

this head namespace is different than the SOAPAction namespace, so I define it like this:

```
@client.request(:ses, "LoginRequest") do |soap|
   soap.namespaces["xmlns:head"] = (namespace here)
   soap.header = {
      "head:Header" => {
         "head:Username" => "asdf",
         "head:Password" => "asdf",
         "head:Application" => "asdf"
      }
    }
end
```

This causes the web server to throw a 500 error, not telling me anything helpful.   The SOAP that is logged to STDOUT I copy and paste into SoapUI, and I run this and it works just fine.

I can't see anything wrong with the XML that it's generating, but it seems like it's being sent with the correct SOAP envelope.

Any ideas on how I can pinpoint the issue?

(Note: if I remove the "head" namespace from the elements I get a valid SOAP response, but it contains "Authentication failed")

**Comment by aungkolatt25** [comment]
# ## ### aaa
