### ISSUE TITLE
Ability to modify SSL options

### ISSUE THREAD

**Issue by rslifka** [savonrb/savon#297]
Hi there,

In upgrading to Savon 1.0, we can no longer attach to HTTPS endpoints as it appears certification verification is now required.  We would like to disable verification via something akin to:

```
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
```

However, there is no way to communicate from Savon > HTTPI > Net::HTTP as the only form of communication appears to be string based (i.e. the 'request' variable is all thats passed from Savon::Client.new all the way down to Net::HTTP).

Thanks!

Rob

**Comment by bjm88** [comment]
Hi - we have a situation with a test SOAP service where we need to use SSL cert and private key to present via client auth from server, however the actual HTTPS hosted cert the domain has is self signed or not valid, host verification wise.  So we want to not verify them, host domain wise, but still present our cert and private key for client auth.....Does Savon support this?

We are having issues when we set ssl_verify_mode: :none
we'll get this error...
HTTPI GET request to wir.dhswir.org (net_http)
HTTPI::SSLError: SSL_read: ssl handshake failure
from /Users/Ben/.rvm/gems/ruby-2.1.5@caredox/gems/httpi-2.0.2/lib/httpi/adapter/net_http.rb:36:in `rescue in request'

if we remove ssl_verify_mode: :none,, then it works...here is the rest of the client initialization.  To test after that we do client.operations

client = Savon.client(log_level: :debug,
                            log: true,
                            filters: [:password],
                            ssl_cert_file: (Rails.root + 'signed.cer').to_s,
                            ssl_cert_key_file: ('private.key').to_s,
                            env_namespace: :soap,
                            namespace_identifier: :urn,
                            namespace: 'urn:cdc:iisb:2011',
                            soap_version: 2,
                            wsdl: "https://example.com/Service?wsdl",
                            endpoint: "https://example.com/Service",
                            open_timeout: 30,
                            read_timeout: 30)

Also note bc/ of this reported issue in 2.3.0 savon we are using 2.2.0

https://github.com/savonrb/savon/issues/491

ANy ideas?

**Comment by matisoffn** [comment]
+1 I'm having this error as well.  Trying to connect to a WSDL service using Savon on Ruby 2.1.4 and Savon 2.10.0 and I'm getting this error.  Have tried setting ssl_verify_mode to no avail.

**Comment by aledustet** [comment]
I can connect using the Net::HTTP library adding a custom certificate like this:
```ruby
http = Net::HTTP.new(host, port)
http.use_ssl = true
http.cert_store = OpenSSL::X509::Store.new
http.cert_store.set_default_paths
raw = File.read('cert_path')
certificate = OpenSSL::X509::Certificate.new raw
http.cert_store.add_cert certificate
```
This connection succeeds. Is there anyway to set the cert_store on the excon or the http connection savon is gonna make?

**Comment by KelseyDH** [comment]
Even though it's not in the documentation, Savon supports `ssl_cert` and `ssl_cert_key` as options, so you don't need to reference a key file.  Thus this will work:

```ruby
      Savon.client(
        # . . .
        ssl_cert: OpenSSL::X509::Certificate.new( ENV["SSL_CERT"] ),
        ssl_cert_key: OpenSSL::PKey::RSA.new( ENV["SSL_CERT_KEY"] )
      )
```

if your key has a password, for `ssl_cert_key` you can also pass:

```ruby
ssl_cert_key: OpenSSL::PKey::RSA.new( ENV["SSL_CERT_KEY"], ENV["SSL_CERT_KEY_PASSWORD"])
```

It would be great if the Savon docs were updated to include these two options for SSL.
