### ISSUE TITLE
SOAP response converted to strange Hash... blame Savon or MegaCorp?

### ISSUE THREAD

**Issue by dvgica** [savonrb/savon#331]
Hi,

Thanks for this gem!

I'm using it to interface to a SOAP service from a company we'll call MegaCorp.  I'm struggling with a response which looks fine in XML, but gives me strange output from `response.to_hash`.

I don't know much about SOAP or WSDL, so I'm not sure if this is a Savon problem, or just the way MegaCorp has written their WSDL.  I can't provide the actual WSDL or response, but I've changed node names and simplified the below example to illustrate.

Here's a snippet of the XML coming back in the SOAP response:

``` xml
<a:History>
  <a:HistoryEvent>
    <a:EventDateTime>2012-04-12T15:01:33.383Z</a:EventDateTime>
  </a:HistoryEvent>
  <a:HistoryEvent>
    <a:EventDateTime>2012-04-25T13:29:44.38Z</a:EventDateTime>
  </a:HistoryEvent>
</a:History>
```

Using `response.to_hash`, it becomes:

``` ruby
{:history => 
  {:history_event=>
    [
      {:event_date_time=>"2012-04-12T15:01:33.383Z"},
      {:event_date_time=>"2012-04-25T13:29:44.38Z"}
    ]
  }
}
```

What I would expect, based on just the XML, is a structure like this:

``` ruby
{:history =>
  [
    {:history_event=>
      {:event_date_time=>"2012-04-12T15:01:33.383Z"}
    },
    {:history_event=> 
      {:event_date_time=>"2012-04-25T13:29:44.38Z"}
    }
  ]
}
```

Here is the relevant part of the WSDL:

``` xml
<xs:complexType name="GetHistoryResponse">
  <xs:sequence>
    <xs:element minOccurs="0" name="History" nillable="true" type="tns:ArrayOfHistoryEvent" />
  </xs:sequence>
</xs:complexType>
<xs:element name="GetHistoryResponse" nillable="true" type="tns:GetHistoryResponse" />
<xs:complexType name="ArrayOfHistoryEvent">
  <xs:sequence>
    <xs:element minOccurs="0" maxOccurs="unbounded" name="HistoryEvent" nillable="true" type="tns:HistoryEvent" />
  </xs:sequence>
</xs:complexType>
<xs:element name="ArrayOfHistoryEvent" nillable="true" type="tns:ArrayOfHistoryEvent" />
<xs:complexType name="HistoryEvent">
  <xs:sequence>
    <xs:element name="EventDateTime" type="xs:dateTime" />
  </xs:sequence>
</xs:complexType>
<xs:element name="HistoryEvent" nillable="true" type="tns:HistoryEvent" />
```

Is this a problem with Savon?  Or should I go harass MegaCorp?

Thanks!

**Comment by jolohaga** [comment]
Anybody looking for a solution to this situation,  I found using `Array.wrap` helped solve it for me.
