### ISSUE TITLE
Timeout when calling service

### ISSUE THREAD

**Issue by link-er** [savonrb/savon#345]
Hello
I'm using savon and have a strange problem - I get Timeout error sometimes. When I tried to make cycle with service request inside I get timeout error on 3-d iteration sometimes, sometimes on 10-th iteration or on 30-th.
There is no problem with the service itself, because from .NET SOAP requests there are no timeout errors.
What can be the problem? Already tried to set read_timeout and open_timeout for a long time, no result.

**Comment by otavionestares** [comment]
Hello guys, I'm having this problem as well...
Rails response: 

Net::OpenTimeout: execution expired when call a request. 

[2018-08-17T13:04:29.413667 #1467] DEBUG -- : HTTPI /peer POST request to adm2.consorcioprimorossiabc.com.br (net_http)
Net::OpenTimeout: execution expired

The request is working on SOAPUI and Chrome Extension Wizdler
