### ISSUE TITLE
XML arguments in operation/action tag under savon 2.0

### ISSUE THREAD

**Issue by courtland** [savonrb/savon#361]
Hi. I am currently in the process of upgrading to savon 2.x from 1.2 and have hit a bit of a wall. I have an obscure API that I must use that requires arguments other than the operation name to be in the SOAP action tag.

For example:

``` xml
<soapenv:Body>

   <inn:PostTransactionRQ PosID="ABC321" RoomID="128" Surname="HERNANDEZ">

      <inn:Service Code="WWW" ReferenceID="123456C" Quantity="2"/>

      <inn:Price AmountAfterTax="0.01" CurrencyCode="USD" DecimalPlaces="2">

         </inn:Price>

   </inn:PostTransactionRQ>

</soapenv:Body>
```

In savon 1.x I had something like:

``` ruby
response = client.request('inn', 'postTransactionRQ',
  # attributes! hash
  { 'PosID' => 'ABC321',
    'RoomID' => '128',
    'Surname' => 'HERNANDEZ'
  }
) do
  soap.body = { ... }
end
```

Where the second and third arguments to the request method yielded an action tag of:

``` xml
<inn:PostTransactionRQ PosID="ABC321" RoomID="128" Surname="HERNANDEZ">
```

So far under savon 2.0 I have not been able to figure out a way to force Gyoku to use an !attributes hash when generating the action/operation tag. I've even looked through the latest Savon code to no avail.

I would prefer to not have to generate the entire message and use the :xml option (overriding Savon Builder). Is there something I am overlooking to accomplish this or can it be added as an option in a new release? Thanks!

**Comment by amoludage** [comment]
@rubiii :+1:
