### ISSUE TITLE
Disable wsdl in Savon 2.0

### ISSUE THREAD

**Issue by rankin** [savonrb/savon#398]
There was another issue with this problem but that was version 0.8. I'm using Savon 2 and I cannot figure out how to disable wsdl in my client. 

The client is prepending wsdl: to my soap request literally

``` xml
<wsdl:AuthRequest/>
```

It should be

``` xml
<AuthRequest/>
```

**Comment by vladlena** [comment]
What is the status for this?
Is it possible to completely remove the wsdl tag from inside the body?
