### ISSUE TITLE
Needed to use message_tag option

### ISSUE THREAD

**Issue by karb** [savonrb/savon#399]
In the docs it says "If you need to use this option, please open an issue let me know why."
Well, I needed it since the WSDL had some imports (#340) that didn't get parsed and thus Savon used the wrong message tag for the method, I had to manually adjust it to be correct. 

Also, the option

    convert_request_keys_to :camelcase

doesn't take the message_tag into account, so I had to CamelCase the symbol :)

**Comment by tjarratt** [comment]
Closing as a duplicate of #340.
