### ISSUE TITLE
SSL detection based on 'https://` protocol not guaranteed to work

### ISSUE THREAD

**Issue by oskarbruening** [savonrb/savon#420]
Here's the issue:
- I have a 3rd party https SOAP server that I need to work with. The url for that server starts with "https", no port provided.
- I provide the url to savon as per documentation: `client = Savon.client(wsdl: 'https://.….')`
- In Savon::Client the URL is passed in to the Wasabi document:
- `@wsdl.document  = @globals[:wsdl]      if @globals.include? :wsdl`
- In the last line of that method HTTPI does a get to the URL to determine the correct URI.
- --> the https uri is changed to "http://....:443/..." = the https protocol is stripped and the ssl port 443 is added
- The problem is that now in HTTPI::Request.ssl? the ssl functionality is determined by !!(url.to_s =~ /^https/)
- --> this now return false because the URI no longer has the protocol listed
- --> the request in Savon fails because HTTPI does not use .use_ssl in the net_http request.

Two options, neither of which I'm a big fan, but wanted to get your feedback:
- Change HTTPI::Request.ssl? to also look for the 443 port
- Have Savon check the protocol in the original URL and force ssl by setting .ssl = true on the HTTPI request.

The workaround is to use the `endpoint` global: 

`client = Savon.client(wsdl: @url, endpoint: @url)`

does the job because Savon::Operation.endpoint checks @globals first to get the url. This is a good work around for us for now, but it's not intuitive and might need to be documented / fixed.

**Comment by swistak** [comment]
thanks for the provided workaround!
