### ISSUE TITLE
Documentation for XML Attributes

### ISSUE THREAD

**Issue by ajrkerr** [savonrb/savon#449]
I think that adding documentation on how to add XML attributes to SOAP requests would be invaluable.  What lead me down this path was some work with the Saleseforce SOAP API which requires attributes to indicate which type of sObject you're working with. 

_Sample XML_

``` xml
<soapenv:Body>
   <urn:create>
      <urn:sObjects xsi:type="urn1:Contact">
         <FirstName>Jane</FirstName>
         <LastName>Doe</LastName>
      </urn:sObjects>
      <urn:sObjects xsi:type="urn1:Account">
         <Name>Acme Rockets, Inc.</Name>
      </urn:sObjects>
   </urn:create>
</soapenv:Body>
```

_Ruby Code_

``` ruby
client.call(:create, {
  :message => {
    :sObjects => [{
        :FirstName => 'Jane',
        :LastName => 'Doe'
      }, {
        :Name => 'Acme Rockets, Inc.'
    }],
    :attributes! => {
      :sObjects => {
        :'xsi:type' => ['urn1:Contact', 'urn1:Account']
      }
    }
  }
})
```

In order to set the xsi:type on each of these I had to go digging through both the Savon and Gyoku code to figure out how it worked and structure my parameters accordingly.  I'm sure this will save someone else some time too.

**Comment by zachfeldman** [comment]
THIS HELPED SO MUCH THANK YOU. @ajrkerr
