### ISSUE TITLE
Duplicate elements in soapbody

### ISSUE THREAD

**Issue by jduhamel** [savonrb/savon#45]
Hi, Thanks for the help earlier. I'm trying to figure out how to get the soap body to handle duplicate elements. like. 

```
 <createAccount> 
   <param>newuser@domain.dom</param> 
   <key>TextMailbox</key> 
   <param> 
     <subKey key="RealName">John Doe</subKey> 
     <subKey key="Password">soappass</subKey> 
   </param> 
 </createAccount> 
```

I find it's difficult to get duplicate param's inserted since it's a hash. Should I do this manually?

-Joe

**Comment by mur-wtag** [comment]
+1 @rubiii

**Comment by anbublacky** [comment]
I have the same problem with the array value, but inside array again i need to pass in the hash value which again gets over written

	result = client.call(:sales_order_list, message: {
		sessionId: session.body[:login_response][:login_return], 
		filters: {filter: 
					{
						item: 
							{key: 'created_at', value: 
								{key: 'from', value: '2016-12-27 00:00:00'}
						}, 
						item: {key: 'created_at', value: 
							{key: 'to', value: '2016-12-27 23:59:59'}
						} 
					}
				}
			})

I tried item inside array still gets overwritten, how do i solve this?
