### ISSUE TITLE
response does not respect :convert_response_tags_to and :strip_namespaces options

### ISSUE THREAD

**Issue by rubiii** [savonrb/savon#474]
`Savon::Response#header` and `Savon::Response#body` currently don't respect the global `:convert_response_tags_to` option and raise a `Savon::InvalidResponseError` if the option
is set to return anything other than a snake_case symbol.

[lib/savon/response.rb#L33](https://github.com/savonrb/savon/blob/41d7ac9a8d890161587a3ce5b8711b58e41ae0bc/lib/savon/response.rb#L33)

i'm going to change all cases of hardcoded snakecase symbols (e.g. `:envelope:` and `:header`)
to use `Nori#find` which respects the `:convert_response_tags_to` option.

**Comment by AparnaData** [comment]
Hello,
I am implementing WSSE security using savon. I got status code 200 and response is blank but raises error `raise_invalid_response_error!': Unable to parse response body: (Savon::InvalidResponseError)
Here is my code
require 'savon'

@client = Savon.client(
    :endpoint                => 'https://example.com',
    :wsdl                    => 'https://example/UserService.wsdl',
    :log                     => true,
    :wsse_auth               => ['Username', 'Password'],
    :pretty_print_xml        => true,
    :convert_request_keys_to => :camelcase,
    :env_namespace           => :s,
    :namespace_identifier    => nil
)

message =  {
    nabp: '1111111',
    ndc: '1234567',
    qty: 30,
    days: 30
}



response = @client.call(:example,
                        :message => message,
                        :soap_header => { "Action" => ""})

response.to_hash[:example_response][:example_result]

Output
/home/admin12/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/savon-2.12.0/lib/savon/response.rb:90:in `raise_invalid_response_error!': Unable to parse response body: (Savon::InvalidResponseError)
""
	from /home/admin12/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/savon-2.12.0/lib/savon/response.rb:72:in `find'
	from /home/admin12/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/savon-2.12.0/lib/savon/response.rb:37:in `body'
	from /home/admin12/RubymineProjects/Wsse/worker.rb:34:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
I, [2018-03-10T12:23:49.932977 #5277]  INFO -- : SOAP response (status 200)
D, [2018-03-10T12:23:49.933051 #5277] DEBUG -- :
