### ISSUE TITLE
Namespace issues in Savon v. 2 

### ISSUE THREAD

**Issue by Michel1975** [savonrb/savon#484]
Hi Rubii,
Nice work you have done with Savon. I have a few challenges getting Savon to work in my project. I am using version 2 in combination with this wsdl-ressource http://sdk.ecmr.biz/src/gateway.asmx?wsdl – an sms gateway for my project. 
I am relatively novice when it comes to handle soap websevices in Rails, so please bear with me.

Before playing aorund with Savon, I sucessfully invoked the push method in SoapUI using the request xml below. Note that in SoapUI I have tested against the version 1.2 of the wsdl operations. The actual message is inserted as a string in element ‘sAlertXml’ using some escaped elements. This is in accordance with wsdl. 

    <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"        xmlns:myb="http://myblipz.com">
    <soap:Header>
      <myb:AuthHeader>
         
         <myb:Login>MyUserName</myb:Login>
         
         <myb:Password>MyPassword</myb:Password>         
      </myb:AuthHeader>
    </soap:Header>
    <soap:Body>
      <myb:Push>
         <myb:iGatewayId>MyGatewayID</myb:iGatewayId>
         
         <myb:sAlertXml><![CDATA[<xml><item><message>Test Message</message><messageid>#2</messageid><recipient>9999999</recipient></item></xml>]]></myb:sAlertXml>
      </myb:Push>
    </soap:Body>
    </soap:Envelope>

In Savon I tried various approaches based on documentation and online articles.

<strong>Approach 1: Using hashes and string generator for sAlert element</strong>

    @wsdl_file = "http://localhost:8088/mockGatewaySoap12?wsdl"  
    client = Savon.client(wsdl: @wsdl_file, env_namespace: :soap, pretty_print_xml: true, namespaces: { "xmlns:myb" => "http://myblipz.com" }, soap_version:2, soap_header: { "AuthHeader" => {"Login" => "MyUsername", "Password" => "MyPassword"}})

    def MessageXml(message, messageid, recipient)
    message = "<xml><item>" + 
      "<message>" + message + "</message>" +
      "<messageid>" + messageid + "</messageid>" +
      "<recipient>" + recipient + "</recipient>" + 
      "</item></xml>"
    return message

<em>Request string in SoapUI Mock Service</em>

    <soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://myblipz.com" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ins0="http://myblipz.com/AbstractTypes" xmlns:myb="http://myblipz.com">
    <soap:Header>
      <AuthHeader>
         <Login>MyUsername</Login>
         <Password>MyPassword</Password>
      </AuthHeader>
    </soap:Header>
    <soap:Body>
      <tns:Push>
         <tns:iGatewayId>GatewayId</tns:iGatewayId>
         <tns:sAlertXml><![CDATA[<xml><item><message>Test-Message</message><messageid>#10</messageid><recipient>9999999</recipient></item></xml>]]></tns:sAlertXml>
      </tns:Push>
    </soap:Body>
    </soap:Envelope>

<em>Result</em>
Didn’t work because (1) namespace prefix is not used in header elements and (2) the namespace prefix ‘tns’ is used instead of ‘myb’ which is required. 

<strong>Approach 2: Using XML-builder and various hacks</strong>

    client = Savon.client(  env_namespace: :soap, 
                            wsdl: @wsdl_file, pretty_print_xml: true, 
                            namespaces: { "xmlns:myb" => "http://myblipz.com" },
                            soap_version:2, soap_header:  %{<myb:AuthHeader><myb:Login>MyUsername</myb:Login><myb:Password>MyPassword</myb:Password></myb:AuthHeader>})

    response = client.call(:push, message: MessageXmlDirect('Test Message', '#6', '99999999'))'

    def MessageXmlDirect(message, messageid, recipient)     
      stringXml = "<xml><item>" + 
        "<message>" + message + "</message>" +
        "<messageid>" + messageid + "</messageid>" +
        "<recipient>" + recipient + "</recipient>" + 
        "</item></xml>"
      xml_body = ""
      builder = Builder::XmlMarkup.new(:target => xml_body, :indent => 2)
      builder.tag!("myb:iGatewayId", "GatewayId")
      builder.tag!("myb:sAlertXml", stringXml)      
      return xml_body 
    end'

<em>Request string in SoapUI Mock Service</em>

    <soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://myblipz.com" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ins0="http://myblipz.com/AbstractTypes" xmlns:myb="http://myblipz.com">
    <soap:Header>
      <myb:AuthHeader>
         <myb:Login>MyUsername</myb:Login>
         <myb:Password>MyPassword</myb:Password>
      </myb:AuthHeader>
    </soap:Header>
    <soap:Body>
      <myb:Push>
         <myb:iGatewayId>GatewayId</myb:iGatewayId>
         <myb:sAlertXml><![CDATA[<xml><item><message>Test Message</message><messageid>#10</messageid><recipient>9999999</recipient></item></xml>]]></myb:sAlertXml>
      </myb:Push>
    </soap:Body>
    </soap:Envelope>

<em>Result</em>

This actually worked in Rails and SoapUI, but when looking at the code there are several open questions:
•	Why do I need to explicitly insert namespace prefix when using xml generated from XML Builder. Shouldn’t this be done automatically in Savon when parsing the message element?
•	Why is the default namespace prefix not used in header elements, the hack used is far from pretty.
•	When I declare one default namespace why is ‘tns’ suddenly added?

So I would to hear your feedback on this matter.Does version 2 allow for a much simpler approach or are you working on new features in version 3 that will fix the namespace issues?

Hope you can help.

Thanks!
BR
Michel

**Comment by bradleesand** [comment]
I believe this was fixed by #590

**Comment by tjarratt** [comment]
zomg +1000000 internet points to you @bradleesand for helping me close an ancient issue. I've needed to revisit some of these older issues and see which are fixed. Having someone chime in and mention this can be closed is extremely helpful.
