### ISSUE TITLE
Formatted text is stripped of formatting and returned as unparseable Nori::StringWithAttributes

### ISSUE THREAD

**Issue by hyyperlite** [savonrb/savon#574]
I need to retrieve a configuration from the server which has pre-formatted text.  The text is returned from the application to Savon in correct format, however Savon then parses the text (incorrectly) removing new lines, spaces etc which makes the text unuseable.   It would be great to have a way to signal Savon for specific SOAP/XML attributes to return it in it's raw form.

Example of formatted message returned from app to Savon:
<config>
# config-version=FAZ100C-5.0-FW-build0266-131108

config system global
    set adom-mode advanced
    set hostname "FAZ100C"
    set timezone 08
end
config system interface
    edit "port1"
        set ip x.x.x.x 255.255.255.0
        set allowaccess ping https ssh http webservice
            config ipv6
            end
    next
    edit "port2"
            config ipv6
            end
    next
    edit "port3"
            config ipv6
            end
    next
end
</config>

Example of string returned by Savon to program:
# config-version=FAZ100C-5.0-FW-build0266-131108config system global    set adom-mode advanced    set hostname "FAZ100C"    set timezone 08endconfig system interface    edit "port1"        set ip x.x.x.x 255.255.255.0        set allowaccess ping https ssh http webservice            config ipv6            end    next    edit "port2"            config ipv6            end    next    edit "port3"            config ipv6            end

The returned string is missing all new line characters and many of the whitespace characters have also been removed.

**Comment by tdevelioglu** [comment]
Short script to test this issue: http://pastebin.com/ZqPRcK3K

We expect:
... HTTP::respond 200 content \" \" noserver\n ... 
We get:
... HTTP::respond 200 content \"\" noserver\n ...

You can see that the " " in 'content &quot; &quot; noserver' gets omitted.

Possible fix: http://pastebin.com/L0Mg7uPz

**Comment by tdevelioglu** [comment]
Just a heads up that the fix didn't work as I was hoping for. It broke parsing savon response to a hash in my tests.
Hoping an author has some more insight.

**Comment by tdevelioglu** [comment]
We need a clean way to strip whitespace characters from the envelope but not from child tags of the body that contain valid response data.
