### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by cliftonm** [savonrb/savon#578]
I've been reading through the comments from a few years ago on this, and nothing has helped but to explicitly define my own XML.  Why does this issue still persist?

Here's the request Savon is generating: (I've removed the data itself from the XML elements for security reasons):

<pre>
&lt;?xml version="1.0" encoding="UTF-8"?>
&lt;env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://TPISoft.com/SmartPayments/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  &lt;env:Body>
    &lt;tns:ProcessCreditCard>
      &lt;tns:UserName>&lt;/tns:UserName>
      &lt;tns:Password>&lt;/tns:Password>
      &lt;tns:TransType>Sale&lt;/tns:TransType>
      &lt;tns:CardNum>&lt;/tns:CardNum>
      &lt;tns:ExpDate>&lt;/tns:ExpDate>
      &lt;tns:MagData>&lt;/tns:MagData>
      &lt;tns:NameOnCard>&lt;/tns:NameOnCard>
      &lt;tns:Amount>&lt;/tns:Amount>
      &lt;tns:Zip>&lt;/tns:Zip>
      &lt;tns:Street>&lt;/tns:Street>
    &lt;/tns:ProcessCreditCard>
  &lt;/env:Body>
&lt;/env:Envelope>
&lt;/pre>
</pre>

The above fails:

<pre>
&lt;soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 &lt;soap:Body>
  &lt;ProcessCreditCardResponse xmlns="http://TPISoft.com/SmartPayments/">
   &lt;ProcessCreditCardResult>
    &lt;Result>1000&lt;/Result>
    &lt;RespMSG>Error - Object reference not set to an instance of an object.&lt;/RespMSG>
   &lt;/ProcessCreditCardResult>
  &lt;/ProcessCreditCardResponse>
 &lt;/soap:Body>
&lt;/soap:Envelope>
</pre>

If I specify my own XML (note the namespace differences):

<pre>
  xml = &lt;&lt;XML
  &lt;soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    &lt;soap:Body>
      &lt;ProcessCreditCard xmlns="http://TPISoft.com/SmartPayments/">
        &lt;UserName>&lt;/UserName>
        &lt;Password>&lt;/Password>
        &lt;TransType>&lt;/TransType>
        &lt;CardNum>&lt;/CardNum>
        &lt;ExpDate>&lt;/ExpDate>
        &lt;MagData>&lt;/MagData>
        &lt;NameOnCard>&lt;/NameOnCard>
        &lt;Amount>&lt;/Amount>
        &lt;InvNum>&lt;/InvNum>
        &lt;PNRef>&lt;/PNRef>
        &lt;Zip>&lt;/Zip>
        &lt;Street>&lt;/Street>
        &lt;CVNum>&lt;/CVNum>
        &lt;ExtData>&lt;/ExtData>
      &lt;/ProcessCreditCard>
    &lt;/soap:Body>
  &lt;/soap:Envelope>
XML
</pre>

Then it works.

I can't believe the namespace is the issue, there must be something else going on.

**Comment by corthmann** [comment]
I had this exact issue as well. My solution was also to just set the entire XML custom:

```
# worked
client.call( :my_operation , xml: <xml-string> )
```
instead of only setting the message:
```
# didn't work
client.call( :my_operation , message: <xml-string> )
```
The funny thing is that the XSL document that created the xml-string is identical - only difference is whether it includes the `<soap:Envelope><soap:Body>` or not.

**Comment by sandip-karanjekar** [comment]
Thanks you saved lot our time.
