### ISSUE TITLE
Had to set element_form_default to :qualified even with WSDL

### ISSUE THREAD

**Issue by edgarjs** [savonrb/savon#608]
Docs say I should open an issue if I have to set the option `element_form_default` and still specified a WSDL.

The WSDL is https://api.escapia.com/EVRNContentService.svc?wsdl

**Comment by radwo** [comment]
Same issue with https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd
