### ISSUE TITLE
Message part was not recognized

### ISSUE THREAD

**Issue by carlhoerberg** [savonrb/savon#625]
Have been running Savon for a long time just fine, but suddenly it started to report:

```
Savon::SOAPFault: (soap:Client) Message part {urn:ec.europa.eu:taxud:vies:services:checkVat}checkVatRequest was not recognized.  (Does it exist in service WSDL?)
```

This is the code: 

``` ruby
c = Savon.client(wsdl: 'http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl')
c.call(:check_vat, message: { countryCode: 'SE', vatNumber: '556074308985' })
```

I've tried the the service here: http://wsdlbrowser.com/soapclient?wsdl_url=http%3A%2F%2Fec.europa.eu%2Ftaxation_customs%2Fvies%2FcheckVatService.wsdl&function_name=checkVat

And it seems to be working. Any idea? I've tried both savon 2.7.2 and 2.6.0. I guess the WSDL changed, but to my untrained eye it looks ok.

**Comment by balamcsd** [comment]
I have same issue, i added wsdl file in service reference and getting this error when trying to access a method please help

**Comment by Dogani** [comment]
Hello If anyone is stuck at this error. Just check the URL to which you submit your soap/xml request.
Mostly you find the message part does not belong to that URL hence rectify and enjoy.
