### ISSUE TITLE
Cannot pass TLSv1_1 or TLSv1_2 configuration options

### ISSUE THREAD

**Issue by saghaulor** [savonrb/savon#639]
After reviewing the httpi code, the gem hardcodes acceptable SSL_VERSIONS. The highest version available to pass as an argument from savon is TLSv1.

It's my understanding that with curl when you specify TLSv1, it will attempt to use the best available version of TLS. I imagine curb does the same thing (though I'm not certain.) 

I have opened a pull request to httpi to support introspecting into OpenSSL to figure out what supported versions are available. This should make httpi compatible with Ruby 1.9+-2.x+

https://github.com/savonrb/httpi/pull/136

After the issue is resolved in httpi, savon will need to be updated to include the newest version of httpi.

**Comment by ReganRyanNZ** [comment]
Requesting to reopen this thread. I'm getting this error trying to access SalesForce with Savon 2.11.2

`UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https`

Seems  like `ssl_version: :TLSv1` is still only TLS 1.0

**Comment by sroller** [comment]
Please see my response on SO.

2017-10-22 22:55 GMT-04:00 Regan Ryan <notifications@github.com>:

**Comment by kapishmalik** [comment]
Requesting to reopen this thread.  I cannot pass TLSv1_1 or TLSv1_2 configuration options.
