### ISSUE TITLE
Multipart requests

### ISSUE THREAD

**Issue by latortuga** [savonrb/savon#640]
Hi Savon folks, thanks for the gem!

I am currently working a project that requires us to send files to a SOAP webservice. We're using version 2 of Savon.

I noticed that Savon supports multipart reponses but there is no built-in support for sending multipart requests - sending multipart form data along with SOAP requests. A few questions:
1. Is this feature request crazy?
2. Is this something that you think would add value to Savon proper?
3. Could it be included in Savon v2?
4. Do you have any general guidelines about how you'd like such a feature implemented? API-wise, I was thinking something like this:

``` rb
client = Savon.client(...)
client.call(:send_file, message: message_xml, attachments: [file1, ...])
```

I'd love to get my hands dirty writing this if it's something you'd accept.

**Comment by tjarratt** [comment]
Hey @latortuga I'm so terribly sorry that it took me so long to respond to this issue. This sounds like an **amazing** feature that would make Savon v2 more featureful and useful.

Did you ever get around to implementing this? I'd love to have something like your proposal in Savon core.

**Comment by latortuga** [comment]
I didn't actually end up implementing this but it's something that I'm definitely still interested in trying to work on. I hesitate to admit this publicly but our solution was pretty embarrassing and ended up looking a bit like a duct-taped abomination of Ruby + [`Kernel#system`](http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-60) + *cough*php*cough*.

I'll move forward using my proposed API!

**Comment by latortuga** [comment]
Did a little digging today and started tinkering a bit and I wanted to run a few things by you before I got too much deeper in the rabbit hole. It looks to me like this feature will require support from the various HTTP libraries - now this isn't necessarily the case, we could simply use `body=` and set the content-type header when some flag is sent to Savon, however it might be easier to simply leverage existing implementations in the various HTTPI adapters. For example, for Net::HTTP, there's the [`multipart-post` gem](https://github.com/nicksieger/multipart-post) and both Rack and curb seem to have multipart support built-in.

I'm thinking that we'd either have to augment HTTPI's adapters to add multipart support for each adapter or add new adapters specifically for multipart support. Do you think a patch to HTTPI would be the best way forward for this or should I concentrate on only supporting this in Savon if the selected HTTPI adapter supports multipart natively?

**Comment by tjarratt** [comment]
Good questions, @latortuga, I honestly haven't thought it through before now. I think that long-term, getting all of the HTTP libraries (curb, net-http, excon, et cetera) to support multipart requests would be a huge win for users of those libraries, but I think an initial stab at support for this should almost certainly follow the happy path, assuming it will work, and failing loudly when it does not, so Savon users understand what failed (and why).

Once that's done, getting better multipart support for the individual adapters would be icing on the cake, in my opinion.

**Comment by Keeguon** [comment]
I'm interested in this as well, @latortuga did you end up tinkering with HTTPI to add multipart and then used those changes in Savon?

**Comment by latortuga** [comment]
I did not ever get around to implementing this as the integration with this partner ended up getting axed.

**Comment by keeguon** [comment]
Okay, so on my side I need this so I started working on an HTTPI fork to support this through the "net/http" adapter. I need to run some tests.

@tjarratt is there any way I can get in touch with you to discuss this whole issue?

**Comment by TheKidCoder** [comment]
Did anyone ever make any headway on this? Now running into this requirement.
