### ISSUE TITLE
basic_auth not working in model

### ISSUE THREAD

**Issue by martineley** [savonrb/savon#642]
We can authenticate fine using this:

`client = Savon.client(wsdl: "http://test1.metapack.com/api/3.x/services/ConsignmentSearchService?wsdl", basic_auth: ["username", "password"])`

but when we move this to a model and use:

`global :basic_auth, "username", "password"`

the web service returns 401

**Comment by weightyfoe** [comment]
I'm sorry to tag onto this, but I am facing something similar but with NTLM auth.

On the console I can do 

c = Savon.client.do
  wsdl "http://blah/blah"
  ntlm ["user", "pass", "domain"]
end
c.call (:method, message)
=> This works just fine, authenticates & returns what I asked for

Translating to a model (using http://savonrb.com/version2/model.html) and I'll just show my changes here:

client wsdl: "http://balh/blah"
global :ntlm, "user", "pass", "domain"

Gives me back 401

I'm guessing that NTLM auth is not being used, and I am not sure why.

**Comment by weightyfoe** [comment]
A bit more info.

I made two clients, to see how they were different.  I made one that works (first one above) and one that does not (using the model):

First (works):
```#<Savon::Client:0x00000007be7cb8 @globals=#<Savon::GlobalOptions:0x00000007be7c68 @option_type=:global, @options={:encoding=>"UTF-8", :soap_version=>1, :namespaces=>{}, :logger=>#<Logger:0x00000007be7bf0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x00000007be7b78 @datetime_format=nil>, @formatter=#<Logger::SimpleFormatter:0x00000007be7a88 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x00000007be7b28 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00000007be7b00 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000007be7ab0>>>>, :log=>false, :filters=>[], :pretty_print_xml=>false, :raise_errors=>true, :strip_namespaces=>true, :convert_response_tags_to=>#<Proc:0x00000007be7a10@/home/jgb/.rvm/gems/ruby-2.0.0-p247/gems/savon-2.11.0/lib/savon/options.rb:85 (lambda)>, :convert_attributes_to=>#<Proc:0x00000007be79e8@/home/jgb/.rvm/gems/ruby-2.0.0-p247/gems/savon-2.11.0/lib/savon/options.rb:86 (lambda)>, :multipart=>false, :adapter=>nil, :use_wsa_headers=>false, :no_message_tag=>false, :follow_redirects=>false, :unwrap=>false, :wsdl=>"http://foo:7057/blah/blah", :ntlm=>["u", "p", "d"]}>, @wsdl=#<Wasabi::Document:0x00000007be7178 @document="http://foo:7057/blah/blah", @adapter=nil, @request=#<HTTPI::Request:0x00000007be7100 @follow_redirect=false, @auth=#<HTTPI::Auth::Config:0x00000007be70b0 @type=:ntlm, @ntlm=["u", "p", "d"]>>>>
```

Second (does not):
```#<Savon::Client:0x00000007b4e158 @globals=#<Savon::GlobalOptions:0x00000007b4e130 @option_type=:global, @options={:encoding=>"UTF-8", :soap_version=>1, :namespaces=>{}, :logger=>#<Logger:0x00000007b4e090 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x00000007b4e040 @datetime_format=nil>, @formatter=#<Logger::SimpleFormatter:0x00000007b4ded8 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x00000007b4dfa0 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00000007b4df78 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000007b4df00>>>>, :log=>false, :filters=>[], :pretty_print_xml=>false, :raise_errors=>true, :strip_namespaces=>true, :convert_response_tags_to=>#<Proc:0x00000007b4ddc0@/home/jgb/.rvm/gems/ruby-2.0.0-p247/gems/savon-2.11.0/lib/savon/options.rb:85 (lambda)>, :convert_attributes_to=>#<Proc:0x00000007b4dd98@/home/jgb/.rvm/gems/ruby-2.0.0-p247/gems/savon-2.11.0/lib/savon/options.rb:86 (lambda)>, :multipart=>false, :adapter=>nil, :use_wsa_headers=>false, :no_message_tag=>false, :follow_redirects=>false, :unwrap=>false, :wsdl=>"http://foo:7057/blah/blah", :ntlm=>["u", "p", "d"]}>, @wsdl=#<Wasabi::Document:0x00000007b4d7a8 @document="http://foo:7057/blah/blah", @adapter=nil, @request=#<HTTPI::Request:0x00000007b4d708 @follow_redirect=false, @url=#<URI::HTTP:0x00000007b750f0 URL:http://foo:7057/blah/blah>, @auth=#<HTTPI::Auth::Config:0x00000007b801f8 @ssl=#<HTTPI::Auth::SSL:0x00000007b801d0 @verify_mode=:peer, @cert=nil>>, @headers={}>>>
```

**Comment by tjarratt** [comment]
Wow! Thanks for the additional information @weightyfoe. Based on the sleuthing you did, it seems pretty clear to me that using `Savon::Model` doesn't work at all with NTLM basic auth right now.

I haven't touched too much of that code, but [the tests for Savon::Model](https://github.com/savonrb/savon/blob/master/spec/savon/model_spec.rb) are pretty clear, if not comprehensive. If anyone is interested in issuing a pull request to fix this defect, I'd be more than happy to provide guidance, answer any questions and merge it when it's done.

**Comment by weightyfoe** [comment]
@tjarratt I'll be quite pleased to see if I can fix this - at the moment I'm parsing arrays of hashes, which is not very nice so getting a proper model to work with would be lovely.

It would be my first time doing this though, so I will definitely need your guidance!

**Comment by weightyfoe** [comment]
@tjarratt Step 1.  I've cloned the repo to my machine, how do I create a Pull Request? :)

**Comment by tjarratt** [comment]
Hey @weightyfoe, sorry I've been incommunicado! Here's a short list of things to do when making a pull request.

* fork the repository -- you should be able to use the 'fork' button in the top right
* clone your fork of the repository locally (e.g.: `git clone git@github.com:weightyfoe/savon`)
* create a feature branch (e.g.: `git checkout -b my-cool-feature`)
* write a failing test for the feature you want to implement
* write some code that makes it pass
* keep working until you're happy with the code
* push your changes back up to your fork on github (e.g.: `git push origin head -u` (this will push the current branch to origin, and set it as the tracking remote))
* now that your feature branch is on github, you should be able to navigate to your fork and create a pull request by clicking the green arrow button for your fork. Just make sure you choose the correct feature branch to issue the pull request from.

**Comment by oranges13** [comment]
So it's been over a year and this issue still appears to be a problem. Has anyone found a workaround or a solution so that we can use the Model with NTLM auth?
