### ISSUE TITLE
Generate XML request without actual HTTP call?

### ISSUE THREAD

**Issue by JeffCohen** [savonrb/savon#643]
Hello,

Thank you for all of your work on savon!

Is there a way to ask the client object to generate the XML of the request, without actually sending it?  I'd like to experiment a bit with various options and see how the generated XML would differ, without actually hitting the server.

I tried to go through all of the documentation, and also called #methods on the client object, but didn't see anything.  Perhaps I'm overlooking something obvious?

Thanks!
Jeff

**Comment by tjarratt** [comment]
Hey @JeffCohen and @SebastianThorn -- sorry I didn't respond sooner.

There's been an option added to Savon recently (as of v2.8.0) that allows you to generate request XML for a given operation. Given a `Savon::Client` this is pretty easy.

```ruby
local_args = {:foo => :bar}
request = savon_client.build_request(:authenticate, local_args) do
  message(:symbol => "AAPL" )
end

puts request.body #prints out relevant XML
```

Does that help? Feel free to reopen this if you'd like. I'm also more than happy to merge pull requests to improve this functionality.

**Comment by JeffCohen** [comment]
Sorry for not seeing your latest comment before now - thank you, that's awesome.
