### ISSUE TITLE
wsdl request do not take into account ssl_verify_mode

### ISSUE THREAD

**Issue by t3hk0d3** [savonrb/savon#645]
Requesting client operations does not tolerate SSL errors.

I've spent few hours before actually understand why `client.operations` cause SSL exception.

https://github.com/savonrb/savon/blob/master/lib/savon/client.rb#L58

It should pass `ssl_verify_mode` here too.

**Comment by ajahongir** [comment]
having same issue, any solutions?

**Comment by coppolaf** [comment]
Same issue here....
It works only id yole specifici ssl_version param  also !!!!

**Comment by ajahongir** [comment]
```ruby
require 'httpclient'
HTTPI.adapter = :httpclient
```
solved my issue.
