### ISSUE TITLE
Usage of 'attributes' needed.

### ISSUE THREAD

**Issue by nlsrchtr** [savonrb/savon#646]
Hi,

thanks for this nice gem. Saved me a lot of time!

In the [documentation](http://savonrb.com/version2/locals.html) it says, I should open an issue, if I needed to use the attributes.

``` ruby
client = Savon.client(wsdl: 'http://longisland.simple-fax.de/soap/?wsdl', log: true, pretty_print_xml: true)
response = client.call(:sendfax, attributes: { 'xmlns:tns' => 'urn:soapservice' }, message: {
  username: '',
  password: '',
  faxnumber: '',
  data: '',
  filetype: '',
  identifier: '',
  statusurl: ''
})
```

Not overwriting the defaults, I was facing the error message `Savon::SOAPFault: (SOAP-ENV:Server) method "urn:Faxservicesendfax" not defined in service`

Maybe this helps to make the gem even better.

**Comment by olleolleolle** [comment]
In order for the 2020 reader to learn what the original poster said, here is a link to the page linked to: https://www.savonrb.com/version2/locals.html
