### ISSUE TITLE
[version 2] response.body invalid, response.hash empty since there is no SOAP header

### ISSUE THREAD

**Issue by rustingibbs** [savonrb/savon#648]
Hi,

The service I am calling at 
http://wstest2.xtm-intl.com/project-manager-gui/services/v2/projectmanager/xop/XTMWebService?wsdl
doesn't return a SOAP header, so response.body is invalid and the response.hash is empty.  How do I work around this?  I would like call the response elements as documented:

response.body
# => { find_user_response: { id: 42, name: 'Hoff' } }

, but I am blocked from doing this.  Do I need to go back to savon v1, or can I inject a dummy SOAP header, or what?

Any help is appreciated.

Thanks,
Rustin

**Comment by tjarratt** [comment]
Hey Rustin, sorry for the delay in responding to this issue. I don't fully understand the issue as you presented it. I don't think there's any code in Savon that *expects* a response to have a soap header, so I don't see this why would fail.

Could you provide a little more information? Did you ever find a workaround for this?

**Comment by pcai** [comment]
Hi @rustingibbs - I'm closing this issue, as we haven't heard from you in some time, please reopen if you still need help with this.
