### ISSUE TITLE
mime-types dependancy clash

### ISSUE THREAD

**Issue by dotemacs** [savonrb/savon#651]
I'm using a gem that uses savon and savon uses wasabi 3.3.0 which uses old mime types. See
```
  In Gemfile:
    my-gem (>= 0) ruby depends on
     savon (= 2.8.0) ruby depends on
        wasabi (= 3.3.0) ruby depends on
          mime-types (< 2.0.0) ruby

    capybara (>= 0) ruby depends on
      mime-types (2.4.3)
```

The problem is that capybara requires a newer version of mime-types gem

**Comment by leyafo** [comment]
bundle update mime-types

**Comment by stan** [comment]
this doesn't fix anything, savon 2.8.0 requires wasabi 3.3.0 which forces mime-types to < 2.0.0

**Comment by anazar** [comment]
+1 -- any update?

**Comment by tjarratt** [comment]
Sorry everyone, this should have been fixed by the last release of wasabi.
