### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by rmevans1** [savonrb/savon#652]
I'm working with a wsdl document that is transmitted over an https connection however when I run client.operations I get the following error:

HTTPI::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certific
ate B: certificate verify failed
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi/adapte
r/net_http.rb:54:in `rescue in request'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi/adapte
r/net_http.rb:38:in `request'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi.rb:159
:in `request'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi.rb:125
:in `get'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/wasabi-3.3.0/lib/wasabi/reso
lver.rb:43:in `load_from_remote'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/wasabi-3.3.0/lib/wasabi/reso
lver.rb:33:in `resolve'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/wasabi-3.3.0/lib/wasabi/docu
ment.rb:142:in `xml'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/wasabi-3.3.0/lib/wasabi/docu
ment.rb:160:in `parse'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/wasabi-3.3.0/lib/wasabi/docu
ment.rb:147:in `parser'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/wasabi-3.3.0/lib/wasabi/docu
ment.rb:64:in `soap_actions'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/savon-2.8.0/lib/savon/client
.rb:28:in `operations'
        from (irb):3
        from C:/Ruby21-x64/bin/irb:11:in `<main>'

**Comment by tjarratt** [comment]
Hey @rmevans1 -- it sounds like your client can't verify the SSL certificate that the server provided. This could be for a variety of reasons

* the server has a self signed cert
* your client doesn't trust the root cert for that domain's certificate authority
* you are actively being MITM'ed

I hope it's not the last option. The first is the most likely, but without inspecting the traffic and trying to debug the problem further, there's not a lot more I can do.

Normally I would apologize for taking so long to respond, but in this case ... this is a pretty common HTTPS error that you should troubleshoot yourself. There really isn't much I can do other than to reassure you that if you learn a bit about SSL certificates, you could probably solve this. Lots of people (myself included) have got Savon to work with a server that uses SSL -- it isn't always easy, but making software work together rarely is.

Much luck with your code!

**Comment by genegc** [comment]
You can also use the ssl_verify_mode global setting to not verify the cert, for testing purposes.
More info here: http://savonrb.com/version2/globals.html
