### ISSUE TITLE
Undocumented change in behavior between 2.1.0 and 2.8.1

### ISSUE THREAD

**Issue by betelgeuse** [savonrb/savon#657]
In 2.1.0 I can call other methods from the context where client.call get called:

```
   67:   def self.foobar_request(method, body)
   68:     client.call method.underscore.to_sym do
   69:       byebug
=> 70:       message body.merge(foobar_access(method))
   71:     end
   72:   end

(byebug) p foobar_access(method)
'return'
```

In 2.8.1

```
(byebug) p foobar_access(method)
Savon::UnknownOptionError Exception: Unknown local option: :foobar_access
nil
```

I am leaving it to you on what behavior is right but at the least this should be documented in CHANGELOG so people know what to expect when upgrading.

**Comment by tjarratt** [comment]
Hey @betelgeuse thanks for reporting this issue. At first I thought there must be something clearly wrong (or maybe missing) in your description of this issue, but upon reflection and investigation it does appear that Savon's implementation of `Savon::Client#call` can accidentally fail to pass messages to the wrong context. 

I'm not sure how to fix this yet, but I do have a failing test on a branch.
