### ISSUE TITLE
XML signatures and X509 certificate

### ISSUE THREAD

**Issue by toncid** [savonrb/savon#658]
Hello!

This topic has been tackled a few times now, but never resolved actually.

In case of X509 signed messages, the signature can be placed at the end of the body message (thus omitting the header completely).

Example XML structure (from: http://stackoverflow.com/questions/13126977/how-to-do-xml-signing-in-ruby):

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Envelope>
  <Body>
    <Message>
      <MessageInfo>
        ...
      </MessageInfo>

      <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
        <SignedInfo>
          <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
          <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
          <Reference URI="">
            <Transforms>
              <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
              <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            </Transforms>
            <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <DigestValue> *** </DigestValue>
          </Reference>
        </SignedInfo>
        <SignatureValue> *** </SignatureValue>

        <KeyInfo>
          <X509Data>
            <X509Certificate> *** </X509Certificate>
          </X509Data>
        </KeyInfo>
      </Signature>
    </Message>
  </Body>
</Envelope>
```

Also, the signed element is not necessarily the `<Body>` element, but can be any of its children.

For example, the `<MessageInfo>` can have the `Id` attribute (`<MessageInfo Id="someMessageId">`) and be linked from `<Reference URI="#someMessageId">`

The certificate info would follow as outlined in the example.

Thoughts?

**Comment by mehmetc** [comment]
Hi,

What would be the benefit(use case) for omitting the header? 

Mehmet

**Comment by toncid** [comment]
It's about extending the message format support to other possibilities available.

My use case is driven by a Croatian regulatory service that required SOAP messages to be in the outlined format.

**Comment by tjarratt** [comment]
Hello @toncid -- thanks for opening this issue. XML signing and x509 certs are definitely one of the toughest parts of Savon to use. 

I'm willing to believe you're correct about the `<Body>` and `<MessageInfo>` points you make above, but I'm not entirely sure what is actionable about this issue. Are you suggesting that Savon should be more flexible in terms of where it puts the signed element and that it should support `<MessageInfo Id="someMessageId">` and `<Reference URI="#someMessageId">`?
