### ISSUE TITLE
How to produce such a output

### ISSUE THREAD

**Issue by chirag7jain** [savonrb/savon#663]
```
<Shipments>
 <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">40665905851</string>
 <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">40665905852</string>
 <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">40665905853</string>
 <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">40665905854</string>
</Shipments>
```
I am unable to find anything in the documentation that helps me out with this

I left the the unwanted portion of my soap xml document

**Comment by tjarratt** [comment]
Hey @chirag7jain. I'm sorry that you're having problems producing the desired XML for the SOAP service you're trying to use. Unfortunately, this is by far the hardest part of the Savon user experience.

In general, you'll want to do something like this:

```ruby
require 'savon'

options = {} # omitted for brevity, possibly includes wsdl
client = Savon.client(options)
client.call(:your_operation_name, message: {Shipments: [40665905851, 40665905852, 40665905853, 40665905854]})
```

Although, the devil is in the details and you'll need to provide the correct hash of arguments to fill out the XML you want to create.

Hope this helps!
