### ISSUE TITLE
Version 2.9.0 doesn't support ruby 1.8.7

### ISSUE THREAD

**Issue by areman** [savonrb/savon#665]
savon-2.9.0/lib/savon/header.rb:65: syntax error, unexpected ':', expecting tASSOC...
savon-2.9.0/lib/savon/header.rb:65: syntax error, unexpected ':', expecting tASSOC
         attributes!: {
savon-2.9.0/lib/savon/header.rb:70: syntax error, unexpected '}', expecting kEND
       })

**Comment by tjarratt** [comment]
Thanks for filing this issue, but I don't think Savon will be supporting older versions of ruby. 1.8.7 in particular is quite old and has been at end of life for some time. 

You should either use an older release of Savon, or upgrade your ruby version. 

Sent From A Very Small Keyboard

**Comment by areman** [comment]
Yes, 
but in the documentaion ( http://savonrb.com/version2/ ) Ruby 1.8.7 is listed as supported version.

**Comment by tjarratt** [comment]
Thanks for pointing that out. Will see about changing the docs soon. 

Sent From A Very Small Keyboard

**Comment by johonas** [comment]
Same issue in version 2.8.10

**Comment by tjarratt** [comment]
Closed by db5d1a1b7fd657b1029b8d0365f9a5d4485717c6
