### ISSUE TITLE
xml_path doesn't work in version3

### ISSUE THREAD

**Issue by tank-bohr** [savonrb/savon#666]
I get this error when try to call `xpath` method on response object
```
NameError: undefined local variable or method `xml_namespaces' for #<Savon::Response:0x0000000341bc18>
from /home/bohr/.gem/ruby/bundler/gems/savon-61e13c61b68e/lib/savon/response.rb:32:in `xpath'```

**Comment by tjarratt** [comment]
Hey @tank-bohr did you mean to file this issue against `Sekken`, which is what Savon v3 turned into?

https://github.com/savonrb/sekken

It's still quite experimental, so it seems you may have found one of the rough edges in there. I would love to merge a pull request if you're willing to fix that up.
