### ISSUE TITLE
README requires an update

### ISSUE THREAD

**Issue by ozgun** [savonrb/savon#675]
Hi,

I've just installed savon by following the instructions in README as below:

```
gem 'savon', '~> 2.8.0'
```

However, it looks like version 2.8.0 has some problems which was mentioned here #651. So, I think README should be updated as below:

```
gem 'savon', '~> 2.10.0'
```

Thanks.

**Comment by tjarratt** [comment]
:+1: Thanks for pointing this out @ozgun. Updating the README really isn't a part of my workflow, but it probably should be :)
