### ISSUE TITLE
NameError: uninitialized constant Savon

### ISSUE THREAD

**Issue by in4systems** [savonrb/savon#677]
Hi, 

I am using ruby 1.8.6. I successfully installed the Savon gem and its dependencies one by one. When i try to run 

"client = Savon::Client.new("http://www.webservicex.net/uszip.asmx?WSDL")"

in the console, I got an error message says "NameError: uninitialized constant Savon"

Please someone help me.

Thanks

**Comment by sroller** [comment]
Last this question came the person forgot to put

    require 'savon'

into their source file.

**Comment by in4systems** [comment]
Thanks sroller,

When I tried require 'savon'

I got the following error message 

"NameError: uninitialized constant OpenSSL::SSL::SSLContext::METHODS"

Thanks

**Comment by sroller** [comment]
which version of Savon are you using? It should be 2.x?

**Comment by in4systems** [comment]
I am using Savon 2.10.0.

Thanks

**Comment by sroller** [comment]
the line should be

    client = Savon.client(wsdl: "your url goes here",
                          pretty_print_xml: true,
                          log_level: :debug,
                          log: true)

**Comment by in4systems** [comment]
Sorry scroller, 

I got the same error message again:

>> client = Savon.client(:wsdl => "your url goes here", :pretty_print_xml => tru
e, :log_level => :debug, :log => true)
NameError: uninitialized constant Savon
        from C:/Users/Sriganeshk/Documents/Schedulemaster/vendor/rails/activerec
ord/lib/../../activesupport/lib/active_support/dependencies.rb:266:in `load_miss
ing_constant'

**Comment by tjarratt** [comment]
Hey @in4systems it sounds like the problem you're having has very little to do with Savon itself. @sroller was correct to point out that you must `require 'savon'` but the OpenSSL error you're seeing is something separate that you must find out yourself. Some googling I did seemed to indicate a possible problem with jruby, but it could be any number of other things.

Good luck in your quest to use savon and ruby!
