### ISSUE TITLE
undefined method `match' for :TLSv1:Symbol

### ISSUE THREAD

**Issue by johonas** [savonrb/savon#678]
I added Savon to my Gemfile:

gem 'savon', '~> 2.0'

When i start the server i get the following exception:

undefined method `match' for :TLSv1:Symbol
app/vendor/bundle/gems/httpi-2.3.0/lib/httpi/auth/ssl.rb:13

I'm using Ruby 1.8.7

**Comment by sroller** [comment]
Which server did you start? Do you have the problem with a plain Ruby script? Perhaps you better this type of question on [Stackoverflow](http://stackoverflow.com/questions/tagged/savon).

**Comment by tjarratt** [comment]
Hey @johonas sorry that you've having this problem. Unfortunately, ruby 1.8.7 is quite old at this point and it's very difficult to continue to support it in addition to ruby 1.9.3 and more modern rubies (2.0 and 2.1 namely). The sad fact is that anyone (myself, @sroller and other delightful people that dedicate their free time to helping out with Savon) gives their time for free, and we don't have time to continue supporting old versions while continuing to help guide Savon to be a high quality ruby gem.

Savon v2.3.0 was the first release that started dropping support for ruby 1.8.7 -- you would best off using one of the 2.3 releases, although you may be able to use Savon v2.4 or maybe 2.5.

**Comment by geo242** [comment]
@johonas Did you ever find a solution to this? I too am running 1.8.7 and don't have the option of upgrading at the moment.

**Comment by jyaworski** [comment]
@geo242 and @johonas:

This is indeed related to ruby 1.8.7, I can confirm that much. 1.9.3 doesn't show this behavior. Try pinning savon at 2.3.0. You may need to pin some of its dependencies as well.

**Comment by pavelvasev** [comment]
this is due to `httpi` gem. if you downgrade httpi to `2.2.7` it passes.
