### ISSUE TITLE
Can't see any operations for specific wsdl

### ISSUE THREAD

**Issue by marcstein** [savonrb/savon#685]
Hi,

I have a wsdl at https://sdkstage.microbilt.com/WebServices/MBCLV11/MBCLV.svc?wsdl that I need to access. Using code that I've used for several years on version 2 I am unable to access any operations.

client = Savon.client(:wsdl => "https://sdkstage.microbilt.com/WebServices/MBCLV11/MBCLV.svc?wsdl")
p client.operations

returns an empty hash

I have been through every post here and every Savon post on StackOverflow and tried a huge range variety of settings, but no success and I'm at wit's end!

What is it about this wsdl that is so problematic? Is it remote XSDs, multiple namespaces, something else?

I can consume it fine using PHP but the overall code is all ruby and I don't want to rewrite the whole thing.

All I need to do is pass an XML body and get a result, e.g.

report = client.call(:get_report, xml: "<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:mes='http://schema.microbilt.com/messages/' xmlns:glob='http://schema.microbilt.com/globals' xmlns:v1='http://schema.microbilt.com/messages/MBCLV/v1_1'>
     <soapenv:Header/>
     <soapenv:Body>
        <mes:GetReport>
           <mes:inquiry>
              <glob:MsgRqHdr>
                 <glob:MemberId>XXXXX</glob:MemberId>
                 <glob:MemberPwd>XXXXX</glob:MemberPwd>
                 <glob:RequestType>N</glob:RequestType>
                 <glob:ReasonCode>3</glob:ReasonCode>
                 <glob:RefNum>12345</glob:RefNum>
              </glob:MsgRqHdr>
              <glob:PersonInfo>
                 <glob:PersonName>
                    <glob:FirstName>Tiffany</glob:FirstName>
                    <glob:LastName>Fraser</glob:LastName>
                 </glob:PersonName>
                 <glob:ContactInfo>               
                    <glob:PhoneNum><glob:PhoneType>1</glob:PhoneType><glob:Phone>6013724455</glob:Phone></glob:PhoneNum><glob:PostAddr>
                       <glob:Addr1>3258 Bayport Circle</glob:Addr1>
                       <glob:City>Annapolis</glob:City>
                       <glob:StateProv>MD</glob:StateProv>
                       <glob:PostalCode>21412</glob:PostalCode>
                    </glob:PostAddr>
                  </glob:ContactInfo>
                 <glob:TINInfo>
                    <glob:TINType>1</glob:TINType>
                    <glob:TaxId>476645846</glob:TaxId>         
                 </glob:TINInfo>
                 <glob:DriversLicense>
                    <glob:LicenseNum>M789456123012</glob:LicenseNum>
                    <glob:StateProv>MN</glob:StateProv>
                 </glob:DriversLicense>
              </glob:PersonInfo>
           </mes:inquiry>
        </mes:GetReport>
     </soapenv:Body>
  </soapenv:Envelope>")

**Comment by marcstein** [comment]
Finally figured it out. Where the wsdl specifies an import, I used that wsdl as the primary in the call and it started working. Thank goodness...I can finally go to sleep.

**Comment by owen2345** [comment]
Hi @marcstein 
I am facing with the same problem, could you pls share how did you solve the problem?
Cheers!
