### ISSUE TITLE
Camelcase

### ISSUE THREAD

**Issue by zdravko** [savonrb/savon#687]
In
convert_request_keys_to :none
it still converts say, CamelCase to :camel_case instead of perhaps :CameCase. Is this a bug, maybe?

**Comment by tjarratt** [comment]
Hey @zdravko I haven't noticed this before, but it seems there may be a bug. Would you be interested in submitting a pull request to fix this? I don't think I will personally have time in the following weeks to investigate this further.

**Comment by zdravko** [comment]
I solved this already. Besides convert_keys_to :none, one needs to set this, too:
:convert_response_tags_to => lambda { |tag| tag }
as Savon.client option.
The above stops converting outgoing parameters  (to XML), while this stops converting the incoming ones.

**Comment by tjarratt** [comment]
Ah, that's a subtle distinction. Thank you for sharing, and thanks for using Savon :)

**Comment by hecbuma** [comment]
@zdravko I have the same issue, where keys get camelized even though I specify `convert_request_keys_to :none` how did you solve this?

**Comment by zdravko** [comment]
This would stop camelizing requests (outgoing) paramters. For responds see above.
