### ISSUE TITLE
My  WSDL is not supported

### ISSUE THREAD

**Issue by alexbron** [savonrb/savon#691]
Hi , 
I want to use the following WSDL : http://api5.silverpop.com/SoapApi?wsdl
When I try to use a simple method login , it creates a sop request that fails on  SchemaValidationError
The working SOAP request looks like this : 
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sil="SilverpopApi:EngageService.SessionMgmt.Login" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    soapenv:Body
        sil:Login
            sil:USERNAMEmymail@gmail.com/sil:USERNAME
            sil:PASSWORDsbcd/sil:PASSWORD
        /sil:Login
    /soapenv:Body
/soapenv:Envelope

while I am getting from the gem following request

<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sil="SilverpopApi:Engageservice" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    soapenv:Body
        sil:Login
            <USERNAME>mymail@gmail.com</USERNAME>
            <PASSWORD>sbcd</PASSWORD>
        /sil:Login
    /soapenv:Body
/soapenv:Envelope

**Comment by tjarratt** [comment]
Hello @alexbron, I'm sorry you're having this problem. Unfortunately, I don't have access to silverpop to check this out, but it does seem that the way Savon is creating the request is incorrect, because the server is returning a Soap Fault.

You may try using another tool like SoapUI to create the correct XML for the silverpop service and compare it to what Savon is generating, and determine what part of the schema is wrong.

Hope this helps!

**Comment by alexbron** [comment]
Hi , I compared the output SOAPUI to Savon , and I found 2 differences:
1.Parameter is written without the namespace USERNAME instead of tns1:USERNAME
2.The namespace is wrong xmlns:tns1="SilverpopApi:Engageservice" instead of xmlns:tns1="SilverpopApi:EngageService.SessionMgmt.Login" 

You do not need access to silverpop in order to check it. I am failing on login.
 You can enter any login data and get SOAP Fault. Once you succeed , you will get a message about wrong credentials.
