### ISSUE TITLE
WSDL problem

### ISSUE THREAD

**Issue by federicolucca** [savonrb/savon#692]
Goodmorning

I must connect a ruby app to an external SOAP service. The supplier gave me a WSDL document for configure the calls. I have some problem with savon like this one below

undefined method `bytesize' for :get_depots:Symbol

I think the problem is that the WSDL has need an another external WSDL for types,but the types are define otherwise in the same WSDL.

Can i send you WSDL and my code for check?

Federico

**Comment by tjarratt** [comment]
Hey @federicolucca thanks for reaching out. The problem you described (e.g. invoking `#bytesize` on the `:get_depots` symbol), sounds like the real problem. Could you provide the full error, with the full backtrace so we can see where that occurred?

The solution you discussed -- namely, the WSDL importing another remote WSDL for types, is a pretty common one. There's an [open issue on Wasabi](https://github.com/savonrb/wasabi/issues/1) (another gem used by Savon) for this, but it hasn't had much progress lately. If that is your problem, you might try amending your WSDL to include the types defined by the external WSDL.

**Comment by federicolucca** [comment]
thanks for the reply.
I did send WSDL by mail, i checked the Wasabi issue and could be the same.

Federico

**Comment by federicolucca** [comment]
i went ahead and finally i had this,from  @client.operations .
[:get_depots, :get_pickup_cutoff_times, :validate_address, :calculate_estimated_time, :get_locations, :get_nearest_depot, :search_consignments, :get_consignment_details, :get_service_codes, :create_pickup_booking, :calculate_cost, :get_qc_codes, :calculate_cost_and_estimated_time]


now  i try @client.call(:calculate_cost) ,where is the error?
![screen shot 2015-05-26 at 12 34 08 pm](https://cloud.githubusercontent.com/assets/2663616/7804539/a8169c4e-03a3-11e5-8197-9ea817fac446.png)

**Comment by tjarratt** [comment]
`builder.rb` is actually in Savon -- I noticed that too earlier, when I was looking at the information you at sent me.

That's the result of setting `:namespaces` to a single string, I believe that expects a hash where the keys are the namespace and the values are URLs.
