### ISSUE TITLE
trying to POST to this API, do i need to pass the env_namespace and namespaces options?

### ISSUE THREAD

**Issue by bhaity** [savonrb/savon#697]
https://ai360.aristotle.com/API2/setIndividualInfoAPI/setIndividualInformationWebService.asmx?op=AddIndividualAndContributionInfo

``` ruby
client = Savon.client(wsdl: "https://ai360.aristotle.com/API2/setIndividualInfoAPI/setIndividualInformationWebService.asmx?WSDL")
client.operations
=> [:set_detail, :add_new_occupation, :add_individual_employer, :update_individual_employer, :add_individual_to_group_by_group_guid, :add_individual_to_group_by_group_and_category_name, :remove_individual_from_a_group, :remove_individual_from_groups_by_category_id, :add_individual_and_contribution_info_with_ind_id, :add_individual_and_contribution_info]

client.call(:add_individual_and_contribution_info, message: donor_hash)
=> Savon::HTTPError: HTTP error (302)
```

**Comment by mrebersv** [comment]
@bhaity I just found Savon, so sorry that this is so late.  HTTP 302 status code is for URL redirection.  When you create your savon client, just tell it to follow redirects:

`client = Savon.client(wsdl: "https://ai360.aristotle.com/API2/setIndividualInfoAPI/setIndividualInformationWebService.asmx?WSDL", follow_redirects: true)`
