### ISSUE TITLE
setting id in XML

### ISSUE THREAD

**Issue by cambridgemike** [savonrb/savon#7]
The API i'm working with requires me to set the id field inside of a tag in the body. So it needs to look something like this:

<customerreferences>
        <customerreference id="1"><![CDATA[]]></customerreference>
</customerreferences>

Is there a way to do this in the hash i'm passing in, or am I going to have to build the body as an XML doc and pass that in (suboptimal).

thanks!

mike

**Comment by Ramanpreetsingh** [comment]
Can anyone post the proposed fix for this, as the link http://github.com/rubiii/savon/issues#issue/35  is not working.
