### ISSUE TITLE
Help Signign Request

### ISSUE THREAD

**Issue by pablojacobi** [savonrb/savon#700]
Hi

I'm currently using Savon to get some info of certain services, but I can't do this in a specific payment gateway that need I sign my calls with a specific private key I have.

I think the closest I am is this

client = Savon.client(wsdl: 'https://webpay3g.orangepeople.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl') do
        wsse_signature Akami::WSSE::Signature.new(Akami::WSSE::Certs.new(private_key_file: 'lib/my_key.key'))
    end

But the server is rejecting me because I'm not giving a private key.

Any help with this issue will be very appreciated.

Thanks in advance

**Comment by tiagocasanovapt** [comment]
Hi there. I see you're trying to make SOAP requests with the Transbank WebpayService.

The Savon client currently only generates the XML signatures for X509 certificates with a BinarySecurityToken tag (at least, that I know of), and that service requires that you pass along a X509IssuerSerial (issuer name & serial number). This issue #658 may have been related with that, but it has gone stale for a while now.

You could/should generate and sign the XML you need with the https://github.com/ebeigarts/signer gem and Nokogiri::XML::Builder while managing your requests/responses with Savon, at least until this client generates the XML like you need it to.

Good luck!
