### ISSUE TITLE
WSDL returning nil operations - is it a WsHttpBinding issue?

### ISSUE THREAD

**Issue by Manitude** [savonrb/savon#702]
Hi, 
I am trying to connect a ruby app with an external WCF webservice.
Details are as follows:
WSDL: http://example.com/DcRegistration/DCRegistrationService.svc?wsdl

My first step was to check it in SOAP-UI. After setting WS-Addressing (Request parameter) to 'true' and checking the 'Add Default wsa:to' checkbox(and ,of course, passing correct request XML), I was able to make a successful call and get a successful reponse from the web-service.

Now, I tried to mimic the same in Ruby.
After reading a lot of documents, I chose Savon for this.
I created a client using:
`client = Savon.client(
    endpoint: "https://example.com/DcRegistration/DCRegistrationService.svc",
    wsdl: "https://example.com/DcRegistration/DCRegistrationService.svc?wsdl",
    namespace: 'http://example.com/it/sa/dcregistration/',
    convert_request_keys_to: :camelcase,
    use_wsa_headers: true,
    soap_version: 2
)`

But When I do `client.operations`, I get a `[]`.
The Savon version I am using is `2.11.1`, my ruby version is `2.0.0`

When I inspected the WSDL I found out it might be because of `WsHttpBinding` being used.
`<wsdl:port name="WSHttpBinding_Registration" binding="i0:WSHttpBinding_Registration">`.

Is there any workaround for this problem?

**Comment by xsmaster** [comment]
Try Savon 3. I can get a WCF Service to connect over HTTP but not HTTPS. Working on that now.

**Comment by mrebersv** [comment]
@Manitude, I just had a similar issue with one WSDL I'm working with.  Found where the parse was happening incorrectly.  In the wasabi gem, lib/parser.rb on line 136, this is the current XPATH search:

`wsdl:definitions/wsdl:binding/wsdl:operation', 'wsdl' => WSDL`

When I changed it to the following (the double slash is necessary), it works:

`wsdl:definitions//wsdl:operation`

I'm not sure if Binding tags are required or not.  You can read about them [here](https://www.w3.org/TR/wsdl#_soap-b).  

@rubiii, As I'm not sure if those tags are required or not, I haven't created a pull request on the wasabi library for this issue (I did fork it, however).  It's seemingly possible, though also seemingly unlikely, that there could be two sets of "operation" elements in a given WSDL with one set outside of the binding tags.  If that is so (and also deemed undesirable), the XPATH I just posted would wrongly grab those operations as well.  If you'd like me to create the pull request, just let me know.

**Comment by Manitude** [comment]
@mrebersv You are right. The problem was indeed while parsing, so I had to change the XPATH to:
`'wsdl:definitions/wsdl:portType/wsdl:operation', 'wsdl' => WSDL` to make it work for my WSDL.
Sorry I didn't update it earlier.
IMO the bindings are perfect and work as expected with _standard_ WSDL(s). But if the elements of WSDL are different from the _standard_ one, this hack becomes necessary.

**Comment by mrebersv** [comment]
As you noted, sometimes you'll see `wsdl:portType` instead of `wsdl:binding` as was the case for me.  This is the reason I changed mine to `wsdl:definitions//wsdl:operation` as the double slash will find children operation elements regardless of if it's `portType`, `definition`, or something else I'm unaware of.
