### ISSUE TITLE
Using `:wsdl` option for new client doesn't work with Savon::SpecHelper

### ISSUE THREAD

**Issue by siannopollo** [savonrb/savon#709]
### Background

I am trying to integrate with a SOAP service and finally got Savon configured to communicate with the SOAP service successfully. Now I want to try to write some tests to verify that I maintain the proper structure, but I'm running into a problem.
### Setup

I have my test setup so that I am mocking Savon as per [the instructions](http://savonrb.com/version2/testing.html). Here is my test code:

```
message = {...} # data in the expected structure
xml_template = fixture_file('result.xml').read # sample response
savon.expects(:grand_total).with(message).returns(response_xml)

result = MyService::Search.new({...}).count # creates a client and calls the :grand_total operation
```

I've cleaned up the code, but in essence I'm following the basic example from the Testing instructions.
### Problem

In my client instantiation code, if I pass a WSDL to `Savon.client`, the test fails; It tries to call the WSDL during the `ensure_exists!` method on `Savon::Operation`. Instead, if I pass an endpoint and a namespace to `Savon.client`, the test passes as I expect.

So, is this expected behavior? I know that Savon (Wasabi, really) loads the remote WSDL to get information about the SOAP service, but I would assume that functionality should be bypassed during the test since we're mocking Savon to avoid unnecessary remote calls.

**Comment by bilby91** [comment]
@siannopollo I run into the same problem. Solved it stubbing the request with `webmock` gem.

A small snippet of the partial spec.

```ruby
    let(:wsdl) {
      File.read('spec/fixtures/wsdl.xml')
    }

    before {
      stub_request(:get, configuration.wsdl)
        .to_return(
          body: wsdl,
          status: 200
        )
     }  
```

I think it would be a good idea to be able to provide the wsdl from a local file in a testing environment. 

Any thoughts on this ?
