### ISSUE TITLE
savonrb vs wsdl with client certificate authentication

### ISSUE THREAD

**Issue by coppolaf** [savonrb/savon#711]
guys, 

i'm going to modify the interface libs of our app that connects to Apple's GSX web services...

they've modified their policy and now the wsdl requires a certifcate to authenticate our connection.

we've received certificates for test and production environments in .pem format directly from apple gsx support techs.

i've made some tests without reaching a valid authentication response...

here is my code (sensitive data stripped!)

```ruby
    # acquires basic client config params from app environment configuration
    service_user = MyApp::Application.config.apple_service_account #gsx username: 'someuser@mydomain.com'
    #
    wsdl_base = MyApp::Application.config.apple_wsdl #https://gsxapiut.apple.com/wsdl/emeaAsp/gsx-emaAsp.wsdl
    #
    cert_file = File.join(Rails.root, 'config', 'cert_store', 'client_cert.pem')


      # initializes the SOAP conection client
      # standard gsx api client
      client = Savon.client do
        wsdl wsdl_base
        namespace 'http://gsxws.apple.com/elements/global'
        namespace_identifier 'glob'
        env_namespace 'soapenv'
        ssl_verify_mode :client_once
        ssl_cert_file cert_file
        # uncomment two lines below to obtain full request and reponse dump
        logger Rails.logger
        log true
      end

      # session opening on gsx wsdl --> method 'authenticate'
      begin
        response = client.call(:authenticate) do
          message "AuthenticateRequest" => { user_id: service_user, service_account_no: '0000xyzxyz', language_code: 'it', user_time_zone: 'CET' }
        end
      rescue Savon::SOAPFault => error
        # logs authentication error!

      end
```

someting extracted from logs:

HTTPI GET request to gsxapiut.apple.com (net_http)
SOAP request: https://gsxapiut.apple.com/gsx-ws/services/emea/asp
SOAPAction: "urn:authenticate", Content-Type: text/xml;charset=UTF-8, Content-Length: 539

```xml
<?xml version="1.0" encoding="UTF-8"?>
   <soapenv:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:glob="http://gsxws.apple.com/elements/global" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
       <glob:Authenticate>
           <AuthenticateRequest>
               <userId>someuser@mydomain.com</userId>
               <serviceAccountNo>0000xyzxyz</serviceAccountNo>
               <languageCode>it</languageCode>
               <userTimeZone>CET</userTimeZone>
           </AuthenticateRequest>
       </glob:Authenticate>
   </soapenv:Body>
</soapenv:Envelope>
```

HTTPI POST request to gsxapiut.apple.com (net_http)
SOAP response (status 401)

```html

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><script type="text/javascript" src="/vpn/resources.js"></script><script type="text/javascript" language="javascript">var Resources = new ResourceManager("/vpn/resources/{lang}", "VPN_ERRORS");</script></head><body><span id="Error: Access is Denied. Client SSL Certificate Required."></span><script type="text/javascript" language="javascript">Resources.Load();</script></body></html>
```

seems the certificate is ignored in sending the request?!?
sure may be i'm using incorrect syntax or missing some params....

waiting your suggestions!!
many thanks in advance for your time

Francesco

**Comment by rogerleite** [comment]
Hi @coppolaf! 

Looking at HTTPI source, on [net_http#setup_ssl_auth](https://github.com/savonrb/httpi/blob/c7934aa12677b16df683103afa4cef94eabf498a/lib/httpi/adapter/net_http.rb#L157), *maybe* you can try to set `ssl_ca_cert_file` on client configuration too.

My another suggestion is to debug via `binding.pry` or even `puts` on `httpi` to see what is going on. You can use bundle to open your local httpi and debug it. On the root of your Rails project, execute `EDITOR=vim bundle open httpi`, and goes to `lib/httpi/adapter/net_http.rb` on line 157.

Hope that helps!
Good luck!

**Comment by coppolaf** [comment]
Roger,

i've done some testing..
some error..

if you're available i may send you the updated source with actual logs..
note that i can't ask you to test this for me because new apple policies,
binds our access to the webservices to 4 parms:
username, sold-to id, the client ssl certificate and the source ip (our
static source ip!!)..
sure i may give you the first 3 parms (they are valid in test env only so
not security sensitive at all!)
but the fourth one.... is impossible to translate or mask!!!

pls specify if you're available to analyze my code and logs to help me
solving this issue!!

many thnaks again for your attention,
regards,


Francesco

**Comment by coppolaf** [comment]
guys, 

after a lot emails vs apple support team (and related pain!!)

it seems we've solved, 
it was more simple than i've supposed....

see the code below:

```ruby
    # acquires basic client config params from app environment configuration
    # gsx service username, sold_to, timezone, language
    service_user = MyApp::Application.config.apple_service_account
    apple_sold_to_id = MyApp::Application.config.apple_sold_to
    apple_lang_code = MyApp::Application.config.apple_lang_code
    apple_time_zone = MyApp::Application.config.apple_time_zone
    # gsx service wsdls
    wsdl_base = MyApp::Application.config.apple_wsdl
    wsdl_iph = nil
    # gsx service certificate and related certificate key
    cert_file = File.join(Rails.root, 'config', 'cert_store', MyApp::Application.config.apple_gsx_cert_file)
    cert_key_file = File.join(Rails.root, 'config', 'cert_store', MyApp::Application.config.apple_gsx_cert_key)


    # initializes the SOAP conection client
    # standard gsx api client
    client_base = Savon.client do
      wsdl wsdl_base
      namespace 'http://gsxws.apple.com/elements/global'
      namespace_identifier 'glob'
      env_namespace 'soapenv'
      ssl_cert_file cert_file
      ssl_cert_key_file cert_key_file
      # uncomment two lines below to obtain full request and response dump
      logger Rails.logger
      log true
    end

    # session opening on gsx wsdl --> method 'authenticate'
    begin
      response = client_base.call(:authenticate) do
        message "AuthenticateRequest" => {user_id: service_user, service_account_no: apple_sold_to_id, language_code: apple_lang_code, user_time_zone: apple_time_zone}
      end
    rescue Savon::SOAPFault => error
      # logs authentication error!
      logger.debug "*************************"
      logger.debug "apple_warranty_check -> fase di login -> codice errore http -> " + error.http.code.inspect
    end
```

**Comment by rogerleite** [comment]
@coppolaf good work! Thanks for updating this issue with solution! :+1:

**Comment by coppolaf** [comment]
Roger...

It was my duty!!!

Many thanks to you for the suggestiona you'gived me in past days!!

Kind regards
Francesco
Il 02/set/2015 03:22 PM, "Roger Leite" <notifications@github.com> ha
scritto:
