### ISSUE TITLE
multi-references seemingly impossible to resolve

### ISSUE THREAD

**Issue by igneus** [savonrb/savon#715]
(described scenario has been tested with savon 2.11.1)

As specified in
https://github.com/savonrb/savon/blob/master/spec/savon/response_spec.rb#L148 ,
multiRef elements (if present in the response XML document) are parsed to an Array.

Having parsed a SOAP response including multiRefs like this

``` xml
...
<multiRef id="id5" soapenc:root="0" soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xsi:type="xsd:int" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">0</multiRef>
<multiRef id="id3" soapenc:root="0" soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xsi:type="xsd:int" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">34</multiRef>
<multiRef id="id1" soapenc:root="0" soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xsi:type="xsd:boolean" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">false</multiRef>
<multiRef id="id4" soapenc:root="0" soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xsi:type="xsd:long" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">0</multiRef>
<multiRef id="id2" soapenc:root="0" soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xsi:type="xsd:int" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">31</multiRef>
...
```

`Savon::Response#body[:multi_ref]` contains an Array like this:

``` ruby
["31", "34", false, "0", "0"]
```

A very important piece of information gets lost this way - the multiRef ids, used in the rest of the document to reference the multiRef content.

As there is no guaranteed order that could be safely used to map ids to indices in the Array, it seems impossible to resolve the references.

I would suggest parsing multiRefs to a Hash like `{:id2 => '31'}` instead of to an Array.

**Comment by billr578** [comment]
I actually think this has more to do with the nori gem than savon.  Savon relies on nori to parse XML into a hash and my guess nori just returns all occurances of "multiRef" that it finds in array form.  I'm resolving this issue by just taking the XML response and jacking it into Nokogiri to solve this issue myself.  I'd assume changing the nori implementation would cause more harm than good to return a hash of multiRef elements instead of an Array.
