### ISSUE TITLE
Savon doesn't see settings from hosts file

### ISSUE THREAD

**Issue by krzyh1989** [savonrb/savon#716]
Hi,
I have problem with connect to API between two servers inside one network. SOAP server nginx redirect from IP to domain (eg: I try http://1.2.3.4/api.php?wsdl and nginx redirect to http://domain.com/api.php?wsdl). So I set in host file (debian system) that 1.2.3.4 is domain.com.

Everything works but without SAVON. I can connect to API by CURL and works correct.

Any ideas how fix it?

**Comment by grzlus** [comment]
You test it with cURL and follow redirects option?

**Comment by krzyh1989** [comment]
Yes I have tested SOAP with cURL and API wokrs. When I try connect by Savon I get timeout but only in this server. In my PC I get response.

**Comment by grzlus** [comment]
Use `follow_redirects` option: https://github.com/savonrb/savon/blob/master/lib/savon/options.rb#L91

This should help you.

**Comment by krzyh1989** [comment]
@grzlus Thanks for help! Everything run fine
