### ISSUE TITLE
Incorrect XML generation

### ISSUE THREAD

**Issue by te-chris** [savonrb/savon#717]
When one makes the message a ruby data structure like so:

```
{"Documents" => [{"Document" => {"Key" => "Value"}},{"Document" => {"Key" => "Value"}}]
```

The XML produced is this:

```
<Documents>
    <Document>
    </Document>
</Documents>
<Documents>
    <Document>
    </Document>
</Documents>
```

Instead of reflecting the nesting arrangement as such

```
<Documents>
    <Document>
    </Document>
    <Document>
    </Document>
</Documents>
```

**Comment by damp42** [comment]
The proper hash for this would be
`{"Documents" => { "Document" => [{"Key" => "Value"}, {"Key" => "Value"}] }}`

**Comment by danielstanojevic** [comment]
@damp42 Thank you.  That helped me out.
