### ISSUE TITLE
Is there a way to create a Savon Client by passing the WSDL String or a Wasabi Document?

### ISSUE THREAD

**Issue by facundofarias** [savonrb/savon#720]
So, maybe this is an improvement (I mean, not an issue) but I was wondering.. is there a way to create a Savon Client by using an String or a Wasabi.document directly instead of providing the WSDL URL?
The question it's mainly because we would like to have some kind of caching of the WSDL documents, and we don't want to use a disk baked cache (as it is recommended on StackOverflow).
Thanks!

**Comment by fiedl** [comment]
This issue has been closed for a while; but for others finding this …

While the readme suggests

```ruby
client = Savon.client(wsdl: 'http://service.example.com?wsdl')
```

one can also provide the wsdl document like this:

```ruby
client = Savon.client do |globals|
  file_content = File.read("/path/to/wsdl")
  globals.wsdl file_content
end
```

In this example, I've read the `file_content` from a file; but one can provide any string, e.g. read it from a database or cache.

More examples in the specs: https://github.com/savonrb/savon/blob/master/spec/savon/client_spec.rb

**Comment by olleolleolle** [comment]
@fiedl Would you care to offer a PR to the README with that example?

**Comment by fiedl** [comment]
@olleolleolle Yes, in principle. But the readme is pretty minimal and this use case might not be very common. I'll just open a minimal PR; feel free to edit or restructure.
