### ISSUE TITLE
Should I reuse the Savon client through an initializer?

### ISSUE THREAD

**Issue by joshuamcginnis** [savonrb/savon#721]
I'm building a service that will use the Savon client and I'm wondering if I should be initializing `Savon.client` on application load or just calling `.client` as-needed in my app?

Any thoughts on this?

**Comment by tjarratt** [comment]
Hey Joshua,

That's a pretty gnarly question. I think the answer is boils down to basically

"How much do you want to insulate yourself from any global state"

vs

"How expensive are object allocations?"

In general, it should be safe to have a single savon client (assuming you aren't using threads or any other concurrency) but it's also pretty fast to create a client. 

But don't take my word for it. Try both and decide for yourself which is better. If you're concerned about speed maybe try benchmarking how slow creating a client is. 

Sent From A Very Small Keyboard

**Comment by joshuamcginnis** [comment]
This is helpful. I think that for our needs, we can just init a new client as it is needed.
