### ISSUE TITLE
Wrong namespace used in request attributes

### ISSUE THREAD

**Issue by nakhli** [savonrb/savon#725]
Trying to connec to the following webservice [https://api.affili.net/V2.0/Logon.svc?wsdl](https://api.affili.net/V2.0/Logon.svc?wsdl).

With the following code

``` ruby
client = Savon.client(wsdl: "https://api.affili.net/V2.0/Logon.svc?wsdl")
message = {'Username' => 'username', 'Password' => 'password', 'WebServiceType' => 'Publisher'}
response = client.call(:logon, message: message)
```

The request generated by Savon:

> HTTPI GET request to api.affili.net (net_http)
> SOAP request: https://api.affili.net/V2.0/Logon.svc
> SOAPAction: "http://affilinet.framework.webservices/Svc/ServiceContract1/Logon", Content-Type:   text/xml;charset=UTF-8, Content-Length: 809
> 
> ``` xml
> <?xml version="1.0" encoding="UTF-8"?>
> <env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"  
>   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
>   xmlns:tns="http://affilinet.framework.webservices/Svc" 
>   xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" 
>   xmlns:ins0="http://affilinet.framework.webservices/types" 
>   xmlns:ins1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" 
>   xmlns:ins2="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation"
>   xmlns:ins3="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WCF">
>     <env:Body>
>       <tns:LogonRequestMsg>
>         <tns:Username>username</tns:Username>
>         <tns:Password>password</tns:Password>
>         <tns:WebServiceType>Publisher</tns:WebServiceType>
>       </tns:LogonRequestMsg>
>    </env:Body>
> </env:Envelope>
> ```
> 
> HTTPI POST request to api.affili.net (net_http)
> SOAP response (status 500)

The problem here is that the `Username`, `Password` and `WebServiceType` are all prefixed with the `tns` namespace whereas the webservice is expecting the to be scoped with the `ins0` namespace. This is the expected message :

``` xml
...
     <tns:LogonRequestMsg>
        <ins0:Username>username</tns:Username>
        <ins0:Password>password</tns:Password>
        <ins0:WebServiceType>Publisher</tns:WebServiceType>
      </tns:LogonRequestMsg>
...
```

Any workaround to set the expected namespace on the request attributes?

**Comment by tothpeter** [comment]
+1

**Comment by nakhli** [comment]
@tothpeter it works if I force the namespace `ins0` on attributes as in:
```ruby
message = {'ins0:Username' => 'username', 'ins0:Password' => 'password', 'ins0:WebServiceType' => 'Publisher'}
```
but I am not sure the namespace id will always be `ins0` and not, for example, `ins1` or `ins2`.

**Comment by tthbalazs** [comment]
@nakhli I don't know if you or anyone else still has this problem, but I also noticed that the namespaces *seem* wrong, BUT in my case the problem really was with the lower camelcasing of the request keys.

Try setting the clients ```convert_request_keys_to: :none``` and see if it works that way. The namespaces seemed to not matter in the end in my case.

**Comment by Arpsara** [comment]
I think I am experiencing the same kind of issue...

Send request:
```xml
  <impl:buyer>
    <impl:shippingAddress>
      <impl:firstName>Doe</impl:firstName>
      <impl:lastName>John</impl:lastName>
      <impl:street1>2 rue test</impl:street1>
      <impl:cityName>Arveyres</impl:cityName>
      <impl:zipCode>33500</impl:zipCode>
      <impl:country>FR</impl:country>
      <impl:phone>06524454377</impl:phone>
    </impl:shippingAddress>
    <ins0:billingAddress>
      <ins0:firstName>Doe</ins0:firstName>
      <ins0:lastName>John</ins0:lastName>
      <ins0:street1>2 rue test</ins0:street1>
      <ins0:cityName>Arveyres</ins0:cityName>
      <ins0:zipCode>33500</ins0:zipCode>
      <ins0:country>FR</ins0:country>
      <ins0:phone>06524454377</ins0:phone>
    </ins0:billingAddress>
    <ins0:lastName>John</ins0:lastName>
    <ins0:firstName>Doe</ins0:firstName>
  </impl:buyer>
```
==> I don't know why, but the shipping address is a "impl" tag, whereas the billing is in a "ins0" (which is the right tag). I send them exactly the same way, by doing something like this:

```ruby
objects = [
     add_address(buyer_data[:shipping_address], :shipping_address),
     add_address(buyer_data[:billing_address], :billing_address)
]

# add_address is a method, so it is sure that the address are the same...

```
Any idea?

Example of what is expected:
```xml
  <ns1:buyer>
    <ns2:title>Mlle</ns2:title>
    <ns2:lastName>BELLE</ns2:lastName>
    <ns2:firstName>Iza</ns2:firstName>
    <ns2:email>iza.belle@yopmail.com</ns2:email>
    <ns2:shippingAdress>
      <ns2:title>Mlle</ns2:title>
      <ns2:name>Maison</ns2:name>
      <ns2:firstName>Iza</ns2:firstName>
      <ns2:lastName>BELLE</ns2:lastName>
      <ns2:street1>4 impasse Aval</ns2:street1>
      <ns2:street2 xsi:nil="true"/>
      <ns2:cityName>Argenteuil</ns2:cityName>
      <ns2:zipCode>95100</ns2:zipCode>
      <ns2:country>FR</ns2:country>
      <ns2:phone>0142000000</ns2:phone>
      <ns2:state xsi:nil="true"/>
      <ns2:county xsi:nil="true"/>
      <ns2:phoneType>1</ns2:phoneType>
    </ns2:shippingAdress>
    <ns2:billingAddress>
      <ns2:title>Mlle</ns2:title>
      <ns2:name>Monext</ns2:name>
      <ns2:firstName>Iza</ns2:firstName>
      <ns2:lastName>BELLE</ns2:lastName>
      <ns2:street1>5, Place de la Pyramide</ns2:street1>
      <ns2:street2>Tour Ariane</ns2:street2>
      <ns2:cityName>PARIS LA DEFENSE - CEDEX</ns2:cityName>
      <ns2:zipCode>92088</ns2:zipCode>
      <ns2:country>FR</ns2:country>
      <ns2:phone>0141000000</ns2:phone>
      <ns2:state xsi:nil="true"/>
      <ns2:county>La Defense</ns2:county>
      <ns2:phoneType>2</ns2:phoneType>
    </ns2:billingAddress>
```
An other problem I'm facing is that the 2.11.3 version of the gem savon doesn't work for me whereas the 2.11.1 works. The tags doesn't work anymore (the are all with the "impl" tag), but I can not figure out why...

**Comment by scarfacedeb** [comment]
I have the same exact issue :(
