### ISSUE TITLE
wsse_signature and wsse_timestamp mutual exclusive

### ISSUE THREAD

**Issue by eiapopeia** [savonrb/savon#727]
Like in #142 I am not able to use wsse_signature and wsse_timestamp config at the same time.
```ruby
Savon.client({
  …
  wsse_timestamp: true,
  wsse_signature: 
    Akami::WSSE::Signature.new(
      Akami::WSSE::Certs.new(cert_file: 'myCert.pem', private_key_file: 'myKey'))
     }
```
Without the other, each peace works.

**Comment by eiapopeia** [comment]
I "fixed" it with the monkey patch referenced in this Akami issue https://github.com/savonrb/akami/issues/15
So this can be closed but should be fixed in Akami.

**Comment by mortee** [comment]
I wonder what the current status of this issue is now. Using 2.11.1 I tried to specify both wsse_auth, wsse_timestamp and wsse_signature, but only the signature is added. Without it, auth and timestamp work.

**Comment by eiapopeia** [comment]
@mortee Please look at the linked akami-issue. There is the fix with a (unfortunately still unmerged) pull request. You can merge it yourself. or use my forked repo.
