### ISSUE TITLE
savon add xmlns to attribute

### ISSUE THREAD

**Issue by zerobatu** [savonrb/savon#728]
Hi
I try to create this xml in the body request

https://gist.github.com/zerobatu/cc9cfb7106a655053394

this is my client config

```
  @@conn = Savon.client(
    wsdl: 'http://localhost:8080/OCCMService.asmx?wsdl',
    log_level: :info,
    env_namespace: :soap,
    namespace_identifier: nil,
    #convert_request_keys_to: :camelcase,
    soap_header: {
      'AuthenticationHeader' => {
        'Username' => @@username,
        'Password' => @@password
      }
    }
  )
```

the problem is with gyoku, when I set convert_request_keys_to like none, this add xmlns to the parameters and the others options doesn't work too

**Comment by wooly** [comment]
I've just been hit with this too. Is there a proper solution for this?
