### ISSUE TITLE
The example wsdl?!!

### ISSUE THREAD

**Issue by ChuckIrvine** [savonrb/savon#731]
Sorry, I'm probably missing something obvious. In order to understand the documentation, I feel like I need access to the example wsdl. However, I can't find this file anywhere. All of the examples simply use something like "http://example.com?wsdl" which isn't a real internet address. Any helpful pointers would be appreciated.

**Comment by HorizonShadow** [comment]
There is no example WSDL. A WSDL just describes the functionality of a web service. You would need to provide that (or use one someone else provides).

**Comment by ChuckIrvine** [comment]
I know that it is the WSDL that describes the functionality of a service. And that's kind of the point. How can I understand savon examples if I can't map them back to the structure of the WSDL? I think the author of the savon documentation has the simple, example wsdl in their mind and just assumes that everyone can simply deduce what that wsdl must be. Perhaps if I were more familiar with SOAP I could do that as well.
