### ISSUE TITLE
WSDL Import Support?

### ISSUE THREAD

**Issue by wingleungchoi** [savonrb/savon#734]
Is it wsdl:import still not supported?

https://github.com/savonrb/savon/issues/618

**Comment by Little-Violette** [comment]
I do not think so, my xsd files import is not worked too

**Comment by rendekarf** [comment]
Hey guys I believe importing (or including?) xsd files are still not supported right ? Is there an alternative way to include the contents of these files, maybe like adding them inline into the wsdl file?
