### ISSUE TITLE
Message Body bad formed

### ISSUE THREAD

**Issue by gnium** [savonrb/savon#737]
Hello. I'm building a request following the documentation and i've been facing that the web service is not getting the proper request.
My code is
```
def banks
 	
 	#msg = "<![CDATA[<CatalogsRequest> <Catalog> <User>xxxx</User> <Pass>xxxx</Pass> <Type>banco</Type> </Catalog> </CatalogsRequest>]]>"
 	client = Savon.client(
 		wsdl: "http://mysuperwerbservice.com/Catalogs.asmx?wsdl",
 		convert_request_keys_to: :camelcase
 	)
 	
	message = {:CatalogsRequest => { :Catalog => { :User => 'XXXX', :Pass => 'XXXX', :Type => 'bank' } }}
	response = client.call(
		:get_catalog, 
			message:  message
			)
 	render json: response, status: 200 
 end
```

The expected message is in the #msg block (commented).
The error i'm getting is this one:

(soap:Server) System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Object reference not set to an instance of an object. at mySuperWebService.GetCatalog(String mixml) --- End of inner exception stack trace ---

**Comment by sroller** [comment]
Have you tried to create a valid request using SoapUI?

**Comment by gnium** [comment]
@sroller yeah! i get the response well. The request is this:

POST xxxxxx HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: text/xml;charset=UTF-8
SOAPAction: "xxxxxxx"
Content-Length: 491
Host: xxxxxxxx
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.3.1 (java 1.5)
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cot="xxxxxxxxx">
   <soapenv:Header/>
   <soapenv:Body>
      <cot:GetCatalog>
         <!--Optional:-->
         
      <cot:mixml>
      <![CDATA[<CatalogsRequest> <Catalog> <User>xxxx</User> <Pass>xxxx</Pass> <Type>banco</Type> </Catalog> </CatalogsRequest>]]>
      </cot:mixml></cot:GetCatalog>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by sroller** [comment]
In worst case you can always build the XML yourself and include a

    xml: "..."

into your call

**Comment by gnium** [comment]
Just tried and the error changed to HTTP error (400)

**Comment by gnium** [comment]
@sroller thanks! i've finally used your suggestion and now it's working properly.
