### ISSUE TITLE
ArgumentError - unknown SSL method `SSLv3'

### ISSUE THREAD

**Issue by jricardooliveira** [savonrb/savon#751]
I'm trying to communicate with a client side certificate to a server which I use to have no problems, but after I update my ruby version and my gems I'm hitting error:

"ArgumentError - unknown SSL method `SSLv3'.

I'm using SAVON gem to communicate with the server... But I get that error that I didn't have before.

Does ruby 2.\* or 1.9\* support SSLv3 no more?

In the same server with openssl s_client:
`
[root@server cert-2016]# openssl s_client -connect  servername.com:401 -cert mycert.cer -key mykey.key -state -quiet
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL_connect:SSLv3 read server hello A
depth=3 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=2 C = PT, O = SCEE, CN = ECRaizEstado
verify return:1
depth=1 C = PT, O = SCEE, OU = ECEstado, CN = ECCE 001
verify return:1
depth=0 C = PT, ST = Lisboa, L = Lisboa, O = Autoridade Tributaria e Aduaneira, CN = www.portaldasfinancas.gov.pt verify return:1
SSL_connect:SSLv3 read server certificate A
SSL_connect:SSLv3 read server certificate request A
SSL_connect:SSLv3 read server done A
SSL_connect:SSLv3 write client certificate A
SSL_connect:SSLv3 write client key exchange A
SSL_connect:SSLv3 write certificate verify A
SSL_connect:SSLv3 write change cipher spec A
SSL_connect:SSLv3 write finished A
SSL_connect:SSLv3 flush data
SSL_connect:SSLv3 read finished A
`

What's wrong? Is it ruby ?

Regards Fak

**Comment by fuelen** [comment]
http://disablessl3.com/
