### ISSUE TITLE
Array being represented as many elements not array with many elements

### ISSUE THREAD

**Issue by fernandes** [savonrb/savon#752]
Sorry if this is a dup issue, I looked for a similar one but haven't found

the problem is, if I wanna send a array os elements, I create the hash normally

``` ruby
{ value: ['name1', 'name2'] }
```

but the message generated is:

``` xml
<value>name1</value><value>name2</value>
```

sure this is not the desired output, a (dirty) workaround is to create the array inside an array

``` ruby
{ value: [['name1', 'name2']] }
```

then the correct XML is generated:

``` xml
<value><element>name1</element><element>name2</element></value>
```

I've looked on the builder, but honestly I have no idea why this is happening, if you could give me some directions I can work on a PR

thank you!

**Update 1:**

As I've seen `Savon::Message` uses `Gyoku` to generate the xml

``` ruby
h = {attrs: [1, 2, 3]}
Gyoku::Array.to_xml(h, "value")
=> "<value><element>attrs</element><element><element>1</element><element>2</element><element>3</element></element></value>"
```

this is what I was expecting for my array

**Comment by askehansen** [comment]
Im having the same issue

**Comment by saygun** [comment]
Same here
