### ISSUE TITLE
Outgoing requests have incorrect xml...

### ISSUE THREAD

**Issue by tkz79** [savonrb/savon#755]
I am having trouble formatting requests to the desired xml... 
API : https://demo.nexorone.com/secure/apiserver.php?wsdl

What I need:

```
<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sec="http://secure.treasury.exchange/">
   <soapenv:Header/>
   <soapenv:Body>
      <sec:GetAccountBalance soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
         <GetAccountBalanceRequest xsi:type="sec:GetAccountBalanceRequest">
            <!--You may enter the following 2 items in any order-->
            <ApiKey xsi:type="xsd:string">xxx</ApiKey>
            <AccountNumber xsi:type="xsd:string">123</AccountNumber>
         </GetAccountBalanceRequest>
      </sec:GetAccountBalance>
   </soapenv:Body>
</soapenv:Envelope>
```

What I am getting:

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:tns="http://secure.treasury.exchange/"
xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
    <env:Body>
        <tns:GetAccountBalance>
            <apiKey>xxx</apiKey>
            <accountNumber>123</accountNumber>
        </tns:GetAccountBalance>
    </env:Body>
</env:Envelope>
```

I saw the configuration for changing variable name styles... so I think I'll be able to sort that out... but why is the tag `<GetAccountBalanceRequest>` completely missing?

**Comment by tkz79** [comment]
Managed to get working by defining xml: exactly as I need it. Feels dirty, but at least its working. Still would love to hear the proper way to handle this so that I can clean it up... please let me know if you can.

**Comment by tkz79** [comment]
Update:
Looks like someone has posted the solution I was hoping for on StackOverflow. 
http://stackoverflow.com/questions/36414069/savon-not-formatting-request-xml-properly

Consequently... closing this issue.

**Comment by slemrmartin** [comment]
I've similar problem:
`opts = {
          wsdl: "https://testmapi.paysec.cz/mapi.svc?wsdl",
          ssl_verify_mode: :none,
      }
      client = Savon.client(opts)

      soap_body = {
          'userName' => credentials[:username],
          'password' => credentials[:password],
          'merchantOrderId' => order.o_id,
          'amount' => price,
      }
      result = client.call(:verify_transaction_is_paid, message: soap_body) do
      end`

generates (posted imported part only)
`<env:Body><tns:userName><userName>xxx</userName><password>xxx</password><merchantOrderId>xxx</merchantOrderId><amount>xxx</amount></tns:userName></env:Body></env:Envelope>`

so there is Deserialisation error because of <tns:userName> tag - tried with savon 2.5 and 2.11

The only solution is construct xml manually without this tag and pass it as client.call(:verify_transaction_is_paid, xml: "..xml string..")

So is this bug in savon?
