### ISSUE TITLE
SOAPAction HTTP header not set correctly

### ISSUE THREAD

**Issue by ajungo** [savonrb/savon#756]
Its setting it as 
SOAPAction: "http://tempuri.org/NewJob"
This is the wsdl
http://adapt.bigadvisory.com/DAPWebSvc/DAPWebSvc.asmx?wsdl

The docs said to open an issue if its not set correctly. Any help would be great!

**Comment by jessiel-hacke** [comment]
the wsdl set the operation as:
`<wsdl:operation name="NewJob">
<soap12:operation soapAction="http://tempuri.org/NewJob" style="document"/>`
