### ISSUE TITLE
Savon does not always handle :content! correctly

### ISSUE THREAD

**Issue by bmattei** [savonrb/savon#772]
If Savon is initialized with element_form_default: :qualified (the default) it converts  the hash key: :content! to "content!".  

Gyoku understands :content! as a keyword indicating the value associated with the key is the content of the element.  When it is converted to "content!" it loses it's meaning to Gyoku. 

Changed 
Savon.client(wsdl: @wsdl_path,
                           encoding: "UTF-8",
                           env_namespace: :soapenv, namespace_identifier: :ns,
                           namespaces: {"xmlns:ns" => "http://www.endeca.com/MDEX/conversation/services/types/3/0",
                                        "xmlns:ns1" => "http://www.endeca.com/MDEX/conversation/XQuery/2009/09"},
                           raise_errors: false,
                           log_level: :debug
                          )

to
Savon.client(wsdl: @wsdl_path,
                           encoding: "UTF-8",
                           env_namespace: :soapenv, namespace_identifier: :ns,
                           namespaces: {"xmlns:ns" => "http://www.endeca.com/MDEX/conversation/services/types/3/0",
                                        "xmlns:ns1" => "http://www.endeca.com/MDEX/conversation/XQuery/2009/09"},
                           raise_errors: false,
                           element_form_default: :unqualified,
                           log_level: :debug
                          )

To work around the problem.  

Found the issue by setting a break point in 
message.rb#to_s.  
- After calling QualifiedMessage.new(@types, @used_namespaces, @key_converter).to_hash(@message, [@message_tag.to_s])

any :content! key is converted to "content!"

**Comment by shkigor** [comment]
I've the same issue. 
Now I have succesfully work of :content! option on the version '2.2.0'

    response = client.call(:create_token, message: {
        :user => userName,
        :param => {
            :@name => "shopId",
            :content! => shopId
        }
    })

**Comment by pcai** [comment]
Thanks for reporting this. I believe this is fixed in https://github.com/savonrb/savon/pull/676 which is released in v2.11.2 - can you give this a try and reopen if you find an issue? Thanks!
