### ISSUE TITLE
Add more info to Readme about `build_request`

### ISSUE THREAD

**Issue by dunyakirkali** [savonrb/savon#776]

**Comment by bobf** [comment]
I may be mistaken but I think this might be in reference to:
http://stackoverflow.com/a/25092044

In which case, the documentation would be about `Savon::Client#operation` and `Savon::Client::build`, which are the two methods used in this external method `get_request` (as per the example).

If I'm mistaken then please correct me, but the original issue doesn't provide any information so I'm trying to supplement it to help get it resolved.

**Comment by dunyakirkali** [comment]
It just wasn't clear to me that it was even possible to look at the raw xml request using `build_request` just by reading the docs.
