### ISSUE TITLE
Namespace not generated as defined.

### ISSUE THREAD

**Issue by donalddylla** [savonrb/savon#779]
My WSDL 1_3/EPayments.wsdl [wsdl.zip](https://github.com/savonrb/savon/files/477602/wsdl.zip) defines multiple namespaces

> &lt;wsdl:definitions xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://epayments.metavante.com/service" xmlns:reqType="http://epayments.metavante.com/types/request" xmlns:resType="http://epayments.metavante.com/types/response" targetNamespace="http://epayments.metavante.com/service" name="MetavanteService"&gt;

However, the SOAP envelope that gets generated not only misses some of the definitions, but changes the value of the xmlns:reqType from http://epayments.metavante.com/types/request to http://epayments.metavante.com/service.

> &lt;soapenv:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:reqType="http://epayments.metavante.com/service" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"&gt;

Savon.client( wsdl: "#{my_dir}/WSDL/v1_3/EPayments.wsdl",
                          env_namespace: :soapenv,
                          endpoint: 'http:///....',
                          log: true,
                          logger:  Logger.new("#{my_dir}/test.log"), 
                          pretty_print_xml: true)

Any idea on why this is happening?

**Comment by silent-e** [comment]
I too am seeing a different namespace in the SOAP envelope than the one that's defined in the WSDL.

Thoughts?  Any suggestions on where to quickly debug this?

(e)

**Comment by silent-e** [comment]
Found that all I needed to to was set the `namespace` config value to what was defined in the WSDL and it finally worked.  Hope this works for you @donalddylla, eight months later.  😄
