### ISSUE TITLE
Provide support to capture HTTP request before sending

### ISSUE THREAD

**Issue by bobf** [savonrb/savon#782]
I found this SO story and saw your comment asking an issue to be created if the feature is desired: http://stackoverflow.com/questions/5860045/view-savon-request-xml-without-sending-to-server

I would like to handle the HTTP transport layer myself so I need a coherent way to capture the final HTTP request, pick it apart, submit it myself, get the response, and then feed that response back into Savon.

Is this something you think can be implemented ? It looks like I can probably hack around with some existing features, maybe using Savon's mocking features, but would be good if I could do this with a thoroughbred API instead.

**Comment by WojtekKruszewski** [comment]
Savon uses HTTPI so maybe you could write an [adapter](http://httpirb.com/#adapters) that modifies request and then delegates to real adapter?

**Comment by pcai** [comment]
@bobf I think you can write an observer to accomplish this. Here is an example from a rails initializer:
```
  # log http SOAP requests to stdout
  if defined?(Savon)
    class SoapObserver
      def notify(operation_name, builder, globals, locals)
        logger = ActiveSupport::Logger.new(STDOUT)
        logger.info operation_name.to_s
        logger.info builder.to_s
        # must return nil to have the request continue
        nil
      end
    end
    Savon.observers << SoapObserver.new
  end
```

But according to http://savonrb.com/version2/observers.html:
> you can also return an HTTPI::Response to mock the request.

So perhaps try that to cancel the request, after you've captured the generated HTTP?
