### ISSUE TITLE
savonrb.com website is not available

### ISSUE THREAD

**Issue by zheileman** [savonrb/savon#785]
Go to http://savonrb.com

It says: `Diese Präsenz ist derzeit nicht verfügbar`.

(not available)

**Comment by cupofjoakim** [comment]
For those in need of documentation right away: A copy from May 8th is available at [web.archive.org](https://web.archive.org/web/20160508033532/http://savonrb.com/)

It may be slightly out of date but it seems to be the best alternative out there right now.

**Comment by cupofjoakim** [comment]
Update: savonrb.com is up again.

**Comment by pcai** [comment]
Thanks for reporting this. Closing since this is now resolved.
