### ISSUE TITLE
How can I set headers when Extending a class?

### ISSUE THREAD

**Issue by Sigularusrex** [savonrb/savon#792]
How can I set headers when using extend Savon::Model in a class?

I can see how this is done in version1, but version2 has no documentation about it (that I  have found)

Thanks

**Comment by Sigularusrex** [comment]
Ok, I've seen another question which happens to have sample code to answer this. 
Using  `self.class.client` in initialize

Example

> def initialize
>     self.class.client wsdl: "http://api.example.com/v1/example?wsdl",
>                       log: true,
>                       log_level: :debug,
>                       pretty_print_xml: true,
>                       soap_header: {
>                           "UserAuthentication" => {
>                               Id: 11111,
>                               Password: "!!!!!!"
>                           }
>                       }
>   end


Additionally what confused me is I need to use 

> soap_header:

 when the documentation for version 2 says to use 

> headers:

**Comment by ErvalhouS** [comment]
Confirmed behavior.

**Comment by oranges13** [comment]
Be careful using self.class.client as it appears Savon does not properly sanitize attributes between requests. See #789 for more info.
