### ISSUE TITLE
Expectations cannot be used multiple times

### ISSUE THREAD

**Issue by joaodiogocosta** [savonrb/savon#795]
We cannot use expectations multiple times. They will take effect only in the first request made.

```ruby
describe 'MyClass' do
  include Savon::SpecHelper

  before(:all) { savon.mock! }
  after(:all) { savon.unmock! }

  before do
    savon.expects(:my_method).returns("...</some_xml>...")
  end

  it '...' do
    # First request works fine
    Savon.client(...).call(:my_method)

    # Second request raises an error
    # Savon::ExpectationError: Unexpected request to the :my_method operation.
    Savon.client(...).call(:my_method) 
  end
```

If you duplicate the following expression it will work as expected:
```ruby
savon.expects(:my_method).returns("...</some_xml>...")
```

This happens because while running through the `expectactions` array here (https://github.com/savonrb/savon/blob/master/lib/savon/mock/spec_helper.rb#L27), the method `shift` is being used and actually eliminating expectations from the array instead of keeping them.

Is this intended behaviour? If not, I'm happy to submit a PR with the fix.

**Comment by datenimperator** [comment]
Ran into this today as well. I guess I'd like something along

```ruby
savon.expects(:my_service_rq, multiple: true).with(message: :any).returns(fixture)
```

What do you think?
