### ISSUE TITLE
Update RubyGems version.

### ISSUE THREAD

**Issue by mamantoha** [savonrb/savon#796]
The last release on RubyGems was the almost year ago. The repository contains some useful thing what we use in production. Can you please release the new version?

Thanks!

**Comment by sroller** [comment]
what's wrong with
`gem update --system`
?

**Comment by mamantoha** [comment]
https://rubygems.org/gems/savon/versions/2.11.1

2.11.1 - June 5, 2015

**Comment by stefansedich** [comment]
+1 wanting to use delete_namespace_attributes and have no realized it was commited days after the last release.

**Comment by wyaeld** [comment]
@tjarratt Are you still a maintainer, and is there any reason why a new release cannot be cut to rubygems?  A lot of enterprisey ruby apps depend quite heavily on this gem.

**Comment by OlivierGrimard** [comment]
+ 1

**Comment by wyaeld** [comment]
@tjarratt @rubiii  I understand you guys might be busy, and if help is required or you need more maintainers for the library, I'm sure if you discuss with the community someone will step up.

However right now, we have over 100 issues piling up, and no-one communicating.  There are a lot of people using this library, some like me probably running quite critical systems for clients.  This is not an acceptable situation.

Things that really need to be confirmed:

1. who has commit access
2. who has the rubygems access
3. who can maintain this library

**Comment by pcai** [comment]
Hey everyone - a new release v2.11.2 is out now which includes commits to master mentioned in this thread, so closing this for now. Please open a new issue if you encounter any problems with this release.

**Comment by wyaeld** [comment]
Hi @pcai its extremely encouraging to see the work you're doing as a maintainer now.  You have my gratitude

**Comment by ioquatix** [comment]
Thanks!
