### ISSUE TITLE
Read Timeout  and Open Timeout is not working.

### ISSUE THREAD

**Issue by joney000** [savonrb/savon#797]
When setting the creating client object : 
`Savon.client(wsdl: wsdl_url, open_timeout: timeout, read_timeout: timeout, ssl_verify_mode: none)`
where timeout = 1 sec .
Request Taking more than 4 sec. but did not get any kind of exception.

**Comment by caseyohara** [comment]
@joney000 I was having the same issue. It appears the issue is actually with recent versions of HTTPI apparently ignoring the timeout settings. Try adding `gem 'httpi', '2.3.0'` to your Gemfile to force an older version.
