### ISSUE TITLE
Support for WS-Reliable Messaging (WS-RM)

### ISSUE THREAD

**Issue by fabiooshiro** [savonrb/savon#806]
I got this error from a microsoft web service:
```
XXX is not supported by this endpoint. Only WS-ReliableMessaging February 2005 messages are processed by this endpoint.
```

**Comment by DamonStamper** [comment]
I am also running into this issue.

**Comment by fabiooshiro** [comment]
Im still waiting for it

**Comment by DamonStamper** [comment]
It'd be rather useful to have this feature.

**Comment by pcai** [comment]
Feel free to open a PR to contribute it. Contributing test cases is also helpful.
