### ISSUE TITLE
Support for Ruby 1.8.7

### ISSUE THREAD

**Issue by blacktea** [savonrb/savon#815]
I've some legacy systems where I need to add SOAP interface.
Using Ruby 1.8.7.
On the website it indicates that Savon 1 or 2 supports Ruby 1.8.7.
However the dependency gem wasabi > 3.3.0 requires mini_portile2 which requires Ruby version >= 1.9.2.
Is there a way to hack the gem to run it on 1.8.7 environment.

**Comment by blacktea** [comment]
Solved by specifying these version in Gemfile

```
gem "mini_portile", '0.6.2'
gem "nokogiri", '1.5.10'
gem "savon", "2.6.0"
gem "wasabi", "3.3.0"
```

**Comment by pcai** [comment]
Hi @blacktea - sorry about the confusion, and thanks for updating with the workaround. It looks like the website is unfortunately out of date. As you discovered, ruby1.8.7 has been unsupported since at least savon 2.11.0, and probably earlier.

**Comment by pcai** [comment]
Closing this for now. I will update the readme with the latest ruby version support info that I have.
