### ISSUE TITLE
Does Savon have any memory leak?

### ISSUE THREAD

**Issue by dlibanori** [savonrb/savon#824]
I have a bunch of sidekiq workers at Heroku and I'm getting [R14](https://devcenter.heroku.com/articles/ruby-memory-use) errors. It starts to worker, get 3 or 4 jobs and then 💣 💥 !

![screen shot 2017-08-15 at 17 55 41](https://user-images.githubusercontent.com/27499/29336058-06c2fcd2-81e3-11e7-8b9f-618b4d331da5.png)

Imho, there are 3 possible reasons:

- my code is buggy
- savon is buggy
- workers really need more memory

What do you think? Any guess?

**Comment by pcai** [comment]
Hi, thanks for reporting. Based on those graphs, it does not appear to be a memory leak, but normally a more controlled reproduction would be necessary to determine if a leak is happening (e.g., run a benchmark/profile that uses savon and records memory usage over time every 1000 calls).

**Comment by dlibanori** [comment]
@pcai, do you think it is 3rd option: "workes really need more memory" ?

Unfortunately these workers use 3rd party service and it is not so easy to profile it

**Comment by pcai** [comment]
That is possible, but like I said, you will need to benchmark or profile the code to really know, but absent that data, I think the next best option is simply test it with a larger dyno and monitor if it does better.

**Comment by pcai** [comment]
Please reopen if you find evidence of a leak in savon with memory profile and (ideally) reproduction steps. We'll do our best to help.
