### ISSUE TITLE
Log failed requests only

### ISSUE THREAD

**Issue by florrain** [savonrb/savon#825]
Hi there,

I'm having issues with a SOAP API and I'm trying to troubleshoot some weird responses (502 errors, long timeouts).

I'd need to put in place a logger that only logs the requests for which the response failed (SoapFault, HTTP Error, ...). I'd like to log the initial request raw body and the response raw body.

How would you accomplish that with Savon 2? (2.10.1)

Thanks

**Comment by kntmrkm** [comment]
I want to see the log too.
