### ISSUE TITLE
Supports write_timeout option

### ISSUE THREAD

**Issue by zentetsukenz** [savonrb/savon#834]
**What is this?**

This option, `write_timeout`, is available in Excon. It provides an ability to set a timeout in request writing operation.

**Why we need this?**

In normal Excon HTTPS request operation, there are 3 events occur in a life cycle of a request, connect, write and read. Savon currently provides `open_timeout` and `read_timeout` settings that are passed to HTTPI which again, in Excon case, are used as `connect_timeout` and `read_timeout`.

It would be better if we could have a fine control over `write_timeout`. Imagine if we have a service which have a very high traffic as a 3rd party. Sometimes that service stalls our request writing operation and do not start processing . But we don't want to wait for it if it doesn't start processing our request yet.

**Comment by HashNotAdam** [comment]
I've created pull request #920 to fix this, however, it seems the test suite is failing on JRuby.

The problem I'm having is that the test suite failed on my computer before I made any changes yet it passes for C Ruby on Travis after my changes.

Given the fragility of the test suite, it's a bit hard for me to get Travis to pass without going for a deep dive into the tests that were already failing. Any insight into this would be appreciated.
