### ISSUE TITLE
Savon(2.11.2) not working with .cer certificate.

### ISSUE THREAD

**Issue by ankurpohekar** [savonrb/savon#840]
I am trying to connect to server using Savon with ssl certificate file `xyz.cer`
my code is as follows
```
client = Savon.client(log_level: :debug,
log: true,
ssl_verify_mode: :none,
ssl_cert_file: '/home/Downloads/xyz.cer',
wsdl: '/home/Documents/test.wsdl'
)

client.call(:initialize)
```
but I am getting an error 

`/.rvm/gems/ruby-2.3.1/gems/httpi-2.4.2/lib/httpi/adapter/httpclient.rb:28:in `rescue in request': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate request A: dh key too small (HTTPI::SSLError)
`

**Comment by tfluehmann** [comment]
It looks like, the problem is not the .cer, the selected diffie-hellman group seems to be too small.
You could try to check the certificate params.
