### ISSUE TITLE
Remove log_level option

### ISSUE THREAD

**Issue by bobbytables** [savonrb/savon#849]
This option can really bite you. Since this option is only applied when a SOAP request is called, it can modify the logger's level in midflight of the process starting.

Take this example:

```ruby
Savon.client(
        wsdl: wsdl_path,
        ssl_version: :SSLv23,
        log: true,
        logger: Rails.logger,
        log_level: :debug
)
```

If your `Rails.logger` has `level` set to `info`, all is well. _Until_ you make a SOAP call using your SAVON client, which then _changes_ the given logger's level to the one in the global options.

This option makes very little sense me, why have this option at all if you're allowing a developer to pass in a Logger? The developer can set the log_level there which will then be used.

I stumbled across this because someone had "debug" on the Savon options log_level, but after a feature was used in production that makes a SOAP call, all of our logs suddenly were spewing SQL log lines (the `debug` level in Rails includes SQL queries). All because we pass in the `Rails.logger` object into the global Savon object.

I really really think this option should be removed, its confusing and it has no need if you're allowing a logger to be passed in.

**Comment by katpadi** [comment]
I also encountered this issue. When you do not define the `logger` it will not affect you though.
