### ISSUE TITLE
Documentation: Include Additional SSL versions in documentation

### ISSUE THREAD

**Issue by Bodacious** [savonrb/savon#855]
The SSL version options listed in the documentation here: 
http://savonrb.com/version2/globals.html

Don't include all of the available options here:
https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/curb.rb#L122-L128

**Comment by pcai** [comment]
Thanks for reporting this. Unfortunately, the savonrb organization has lost control of this domain (nobody I can reach has had write access to the website for several years now).
