### ISSUE TITLE
Savon does not allow to disable proxy defined by http_proxy env

### ISSUE THREAD

**Issue by obfuscoder** [savonrb/savon#858]
Env:

Ubuntu 17.10
Ruby 2.3.4
Savon 2.11.1

Steps to reproduce:

- Set env variable `http_proxy` to point to a proxy
- Instantiate and call a Soap service

It turns out, the underlying HTTPI picks up the env variable and connects to the Soap service via the proxy defined in the http_proxy env (or https_proxy env if the Soap service is hosted on https).

It is impossible to disable this behavior by using `proxy: nil` during the instantiation of the Savon soap client.

**Comment by obfuscoder** [comment]
Is this project dead?

**Comment by pcai** [comment]
Have you tried upgrading savon? The nil proxy option was added in the 2.12 release.
