### ISSUE TITLE
Can ANYONE help??? Passing an array of complex type elements for Savon 2 (SOAP)

### ISSUE THREAD

**Issue by gangelo** [savonrb/savon#860]
Originally posted [here](https://stackoverflow.com/questions/49262848/passing-an-array-of-complex-type-elements-for-savon-2-soap)

I am trying to send a SOAP request using **Savon** and **message** and I'm getting this error

    #<Savon::SOAPFault: (a:InternalServiceFault) Object reference not set to an instance of an object.>

(note: when I call Savon#call using xml (i.e. savon.call(:operation, xml: xml_payload), I have no problems receiving a successful response)

**The soap request envelope looks like this**

    <soapenv:Envelope 
    	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
    	xmlns:tem="http://tempuri.org/" 
    	xmlns:real="http://schemas.datacontract.org/2004/07/SomeWhere.Taxaware.Api">
       <soapenv:Header/>
       <soapenv:Body>
          <tem:CalculateInvoiceTax>
             
             <tem:invoiceRequest>
                
                <real:CustomerAccountNumber>123</real:CustomerAccountNumber>
                
                <real:InvoiceId>I123</real:InvoiceId>
                
                <real:InvoiceLineItems>
                   
                   <real:InvoiceLineItem>
                      
                      <real:DollarAmount>100</real:DollarAmount>
                      
                      <real:FreightAmount>0</real:FreightAmount>
                      <real:InvoiceItemId>123</real:InvoiceItemId>
                      
                      <real:Quantity>1</real:Quantity>
                   </real:InvoiceLineItem>
                   <real:InvoiceLineItem>
                      
                      <real:DollarAmount>200</real:DollarAmount>
                      
                      <real:FreightAmount>0</real:FreightAmount>
                      <real:InvoiceItemId>456</real:InvoiceItemId>
                      
                      <real:Quantity>2</real:Quantity>
                   </real:InvoiceLineItem>
                </real:InvoiceLineItems>
                
                <real:IsAuditable>1</real:IsAuditable>
                
                <real:ShipToCity>Cambridge</real:ShipToCity>
                
                <real:ShipToCountry>USA</real:ShipToCountry>
                
                <real:ShipToPostalCode>02139-4121</real:ShipToPostalCode>
                
                <real:ShipToStateProvince>MA</real:ShipToStateProvince>
                
                <real:TaxDate>2018-02-03T08:22:54</real:TaxDate>
                
                <real:TaxwareCompanyCode>123</real:TaxwareCompanyCode>
             </tem:invoiceRequest>
          </tem:CalculateInvoiceTax>
       </soapenv:Body>
    </soapenv:Envelope>

**The part I believe I'm having trouble with is this Ruby Hash representation of the InvoiceLineItems element which consists of a complex type**

    <xs:complexType name="ArrayOfInvoiceLineItem">

**The Ruby Hash representation and call I've been using is**
 

    message = {
                    customer_account_number: '1100087',
                    invoice_id: 'I1603079660',
                    invoice_line_items: [
                        {
                            dollar_amount: 100,
                            freight_amount: 0,
                            invoice_item_id: '24663424',
                            quantity: 1
                        }
                    ],
                    is_auditable: 1,
                    ship_to_city: 'Cambridge',
                    ship_to_country: 'USA',
                    ship_to_postal_code: '02139-4121',
                    ship_to_state_province: 'MA',
                    tax_date: '2018-02-03T08:22:54',
                    taxware_company_code: '01'
                }
    
    soap_client = Savon.client do | locals |
              locals.wsdl = '[the endpoint]'
              locals.convert_request_keys_to :camelcase
            end
    
    response = soap_client.call(:calculate_invoice_tax, message: message)

**A resulting error is thrown**

     #<Savon::SOAPFault: (a:InternalServiceFault) Object reference not set to an instance of an object.>

**How do I represent the given SOAP envelope as a Hash that Savon will accept?**

The following post was somewhat helpful, but it doesn't deal with complex types: [https://stackoverflow.com/questions/20982594/passing-array-elements-for-savon-2-soap][1]

  [1]: https://stackoverflow.com/questions/20982594/passing-array-elements-for-savon-2-soap

**Comment by JanDintel** [comment]
@gangelo I just experienced the same issue and found a solution. You can configure this behavior as a global using the unwrap key. This key is given as an option to `Gyoku` which generates the XML for `Savon`.

```ruby
client = Savon.client(wsdl: 'https://example.com/wsdl', unwrap: true)
client.call(:cook_meal, message: { 'Ingredients' => ['tomato', 'basil', 'mozzarella'] })
```

Although the issue is old, better late than never.
