### ISSUE TITLE
namespace_identifier throws when nil

### ISSUE THREAD

**Issue by metekabak** [savonrb/savon#863]
NoMethodError (undefined method `[]' for nil:NilClass):

`client = Savon.client(wsdl: 'https://www.regonline.com/api/default.asmx?WSDL',
                              convert_request_keys_to: :none,
                              namespace_identifier: nil)`

**Comment by jainnimish7** [comment]
@metekabak It doesn't seems any error in this code.
I run the above code you provided. But It is returning Savon::Client object, like it should. <Savon::Client:0x0000000002948db8> Please check again and let us know.

**Comment by pcai** [comment]
Please reopen when you can provide reproduction steps and ruby/savon version. Thanks!
