### ISSUE TITLE
Soap v1.2 cannot be set

### ISSUE THREAD

**Issue by swigrid** [savonrb/savon#872]
# Bug report

**Current behavior:**
When soap version is set to 1.2 `soap_version: 1.2` and client is called there is an exception
```
NoMethodError: undefined method `%' for nil:NilClass
from /Users/roman/.rvm/gems/ruby-2.1.4@mob/gems/savon-2.12.0/lib/savon/request.rb:105:in `configure_headers'
```

**Steps to reproduce current behavior:**

```
client = Savon.client(wsdl: "https://url.com/service?wsdl", basic_auth: ['name', 'pass'], soap_version: 1.2)
response = client.call(:action, message: {id: 1})
```

**Expected behavior:**
not to crash

**System information:**
mac os

* ruby version: 
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin16.0]
* savon version: 
savon (2.12.0)

**Comment by bengalamx** [comment]
Same issue here 🙋🏼‍♂️

**Comment by bengalamx** [comment]
@swigrid Any suggestions?

**Comment by swigrid** [comment]
Try setting soap_version: 1.

It looks like it’s setting content type based on version, but there is only 1 and  2.

https://github.com/savonrb/savon/blob/master/lib/savon/request.rb

I am not sure if it is enough to set just version 1 and it covers also 1.2

**Comment by bengalamx** [comment]
Hi @swigrid, still having the same issue, I tried soap_version in very different ways : '1', 1, '1.2', 1.2, 12, '12'. The strange thing is that the client is returning the full list operations of the WSDL, so it seems to work, but when doing a client.call everything broke.

**Comment by bengalamx** [comment]
@hoverlover can u help us? 😅

**Comment by bengalamx** [comment]
Hey @swigrid it seems is working with `soap_version: 2`, you should give it a try.

**Comment by hoverlover** [comment]
Hey @bengalamx.  It sounds like maybe you figured it out.  If not, I'd ask another committer on this project.  It's been a really long time since I've worked on it.

**Comment by hoverlover** [comment]
I just took a quick look, however, and it looks like specifying version 1.2 is not valid.  [This](https://github.com/savonrb/savon/blob/v2.12.0/lib/savon/request.rb#L105) line tries to look up the content type in the [Hash](https://github.com/savonrb/savon/blob/v2.12.0/lib/savon/request.rb#L78-L81) using the specified SOAP version.  That Hash only supports either version 1 or 2, which is why you're getting `nil` on that line.
