### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by elieteyssedou** [savonrb/savon#876]
# Bug report

**Current behavior:**
savonrb.com is down... 😢
<img width="832" alt="capture d ecran 2018-07-11 a 10 59 14" src="https://user-images.githubusercontent.com/8143621/42561573-c047b548-84f9-11e8-8bfc-f6b3e77936e9.png">

**Steps to reproduce current behavior:**
Try to visite savonrb.com

**Expected behavior:**
The savon's website should display.

Is there another way to access a - complete - documentation of savon ?

**Comment by jamesgecko** [comment]
The source for the website is [available here](https://github.com/savonrb/savonrb.com/tree/master/source/version2), but it looks like it hasn't been updated for five years.

**Comment by elieteyssedou** [comment]
Thanks @jamesgecko
