### ISSUE TITLE
edit Envelope line

### ISSUE THREAD

**Issue by AkashkumarDev** [savonrb/savon#878]
is there way to edit Envelop area ?

with Savon build request is ( getting 500 error )

      <?xml version="1.0" encoding="UTF-8"?>
      <SOAP-ENV:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://fedex.com/ws/rate/v24" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
       <SOAP-ENV:Body>
          <ns1:RateRequest>
              <ns1:WebAuthenticationDetail>
                  <ns1:UserCredential>

with PHP client ( working )

      <?xml version="1.0" encoding="UTF-8"?>
      <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://fedex.com/ws/rate/v24">
         <SOAP-ENV:Body>
           <ns1:RateRequest>
               <ns1:WebAuthenticationDetail>
                   <ns1:UserCredential>

i wish there could way to make Envelope line same as PHP client so make Savon usable

Thanks

**Comment by adarsh-gov** [comment]
It looks like you are trying to edit the namespaces in the `<Envelope>` tag.

Here's how I would configure your client given what I ended up doing, using the main `namespace` config and then another `namespaces` additional config.

LMK if it works for you. If so, we should ensure it gets added to the documentation.

```
client = Savon.client(
  endpoint: "http://example.com/endpoint",
  env_namespace: "SOAP-ENV",
  namespace: "http://schemas.xmlsoap.org/soap/envelope/",
  namespaces: { "xmlns:ns1" => "http://fedex.com/ws/rate/v24" },
  raise_errors: true,
  log: debug,
  log_level: :debug,
  pretty_print_xml: true
)
```
