### ISSUE TITLE
Array/hash confusion

### ISSUE THREAD

**Issue by nut707** [savonrb/savon#883]
When savon parse xml as below
```
<MessageList>
    <TradeMessage ID="4850644"/>
    <TradeMessage ID="4850645"/>
    <TradeMessage ID="4850665"/>
    <TradeMessage ID="4850666"/>
    <TradeMessage ID="4850667"/>
    <TradeMessage ID="4850712"/>
    <TradeMessage ID="4850716"/>
    <TradeMessage ID="4850719"/>
    <TradeMessage ID="4850745"/>
</MessageList>
```

it return hash `{MessageList: TradeMessage: [{@id: '123'},...,{@id: '456'}]}`

But if xml will be like
```
<MessageList>
    <TradeMessage ID="4850644"/>
</MessageList>
```
It will return `{MessageList: TradeMessage: {@id: '123'}}`
So i can't loop through Message list because it can be hash or array. 
My code to loop through array: 
```
t[:message_list][:trade_message].each do |m|
    TradeMessage.create(id: m[:@id])
end
```
What to do in such situation? Should i change xml parser from deafult nokogiri to smth else?

**Comment by pcai** [comment]
Please ask questions on StackOverflow. Questions or support requests will be closed.
https://stackoverflow.com/questions/ask?tags=savon

Bug reports should [follow the bug report template](https://github.com/savonrb/savon/issues/new?template=Bug_report.md) - thanks

**Comment by pokonski** [comment]
Too bad authors of Savon don't answer the questions asked there.
