### ISSUE TITLE
Removal of WSDL Method name from generated XML

### ISSUE THREAD

**Issue by hamzaaltaf** [savonrb/savon#886]
I am sorry I don't know if this is an issue or feature request. I googled but couldn't find the answer, therefore, posting it here.

I am generating the SOAP using following code

@client = Savon.client(wsdl: "https://easypaystg.easypaisa.com.pk/easypay-service/PartnerBusinessService/META-INF/wsdl/partner/transaction/PartnerBusinessService.wsdl",
ssl_verify_mode: :none,
log: true,
log_level: :debug,
pretty_print_xml: true,
env_namespace: :soapenv,
namespaces: {"xmlns:soapenv" => "http://schemas.xmlsoap.org/soap/envelope/",
	"xmlns:dto" => "http://dto.transaction.partner.pg.systems.com/",
       "xmlns:dto1" => "http://dto.common.pg.systems.com/"}
)

message = {
"dto:initiateTransactionRequestType": { "dto1:username": "xyz@gmail.com", "dto1:password": "adasdasdasdsadasddas", channel: "internet", storeId: "4886", transactionType: "MA", msisdn: "M", mobileAccountNo: "+xxxxxxxxxx", emailAddress: "xyz@gmal.com" }
}
		@client.call(:initiate_transaction,
			:message => message, soap_action: false
)

<soapenv:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsdl="http://transaction.partner.pg.systems.com/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:dto="http://dto.transaction.partner.pg.systems.com/" xmlns:dto1="http://dto.common.pg.systems.com/">
  <soapenv:Body>
    **<wsdl:initiateTransaction>**
      <dto:initiateTransactionRequestType>
        <dto1:username>xyz@abc.com</dto1:username>
        <dto1:password>asdssadasdasdasdsa</dto1:password>
        <channel>internet</channel>
        <storeId>4886</storeId>
        <transactionType>MA</transactionType>
        <msisdn>M</msisdn>
        <mobileAccountNo>xxxxxxxx</mobileAccountNo>
        <emailAddress>abc@gmail.com</emailAddress>
      </dto:initiateTransactionRequestType>
    </wsdl:initiateTransaction>
  </soapenv:Body>
</soapenv:Envelope>

But the service requires 

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:dto="http://dto.transaction.partner.pg.systems.com/" xmlns:dto1="http://dto.common.pg.systems.com/">
**<soapenv:Header />
<soapenv:Body>
<dto:initiateTransactionRequestType>**
<dto1:username>pgsystems</dto1:Username>
<dto1:password>9b01234324vxddc0b</dto1:Password>
<channel>Internet</channel>
<orderId>000000001</orderId> <storeId>465</storeId>
<transactionAmount>5000.00</transactionAmount>
<transactionType>OTC</transactionType>
<msisdn></msisdn>
<mobileAccountNo>034632401722</mobileAccountNo>
<emailAddress>abc@test.com</emailAddress>
</dto:initiateTransactionRequestTyp
e>
</soapenv:Body>
</soapenv:Envelope>

Only difference between the system required Envelope and mine is this **<wsdl:initiateTransaction>** .So the problem is SAVON adds the <wsdl:initiateTransaction> tag to the request automatically when I use @client.call(:method) function, kindly help me out with this issue

**Comment by bonol** [comment]
I am using Savon v2.12, have similar issue with SAVON default Envelope tag, though mine is slightly different. Here is my code.

client = Savon.client(
    endpoint: "http://servicesuat.courierpost.co.nz",
    wsdl: "http://services.courierpost.co.nz/ECL.Online/ECL_Online.svc?singleWsdl",
    basic_auth: ["user", "password"],
    convert_request_keys_to: :none,
    log: true,
    log_level: :debug,
    pretty_print_xml: true,
)
request_message = {MessageID: "Valid Pricing Test", MessageDateTime: "2012-04-13T10:50:55", BusinessUnit: "CP", AccountNumber: "12345678", ReturnData: "Pricing"}
client.call(:change_log, message: request_message)

And I got this in body.

<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:q9="http://ECL.Online/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ins0="http://schemas.microsoft.com/Message" xmlns:ins1="http://ECL.Online.BT.JobBooking.JobBooking_v1_6_XML.xsd" xmlns:ins2="http://ECL.Online.BT.JobBooking.JobBookingResponse_v1_5_XML.xsd" xmlns:ins3="http://ECL.Online.BT.ScanEvent.ScanEventRequest_v1_5_XML" xmlns:ins4="http://ECL.Online.BT.ScanEvent.ScanEventData_v2_2_XML.xsd" xmlns:ins5="http://ECL.Online.BT.Manifest.ManifestRequest_v1_4_XML.xsd" xmlns:ins6="http://ECL.Online.BT.Manifest.ManifestResponse_v1_2_XML.xsd" xmlns:ins7="http://ECL.Online.BT.Preadvice.Preadvice_v1_5_XML.xsd" xmlns:ins8="http://ECL.Online.BT.Preadvice.PreadviceResponse_v1_0_XML.xsd" xmlns:ins9="http://ECL.Online.BT.ChangeLog.ChangeLogRequest_v1_0_XML.xsd" xmlns:ins10="http://ECL.Online.BT.ChangeLog.ChangeLogResponse_v1_2_XML.xsd">
  <env:Body>
    <ins9:ChangeLogRequest>
      <ins9:MessageID>Valid Pricing Test</ins9:MessageID>
      <ins9:MessageDateTime>2012-04-13T10:50:55</ins9:MessageDateTime>
      <ins9:BusinessUnit>CP</ins9:BusinessUnit>
      <ins9:AccountNumber>12345678</ins9:AccountNumber>
      <ins9:ReturnData>Pricing</ins9:ReturnData>
    </ins9:ChangeLogRequest>
  </env:Body>
</env:Envelope>

I successfully made the request working with Postman.

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
xmlns:ins9="http://ECL.Online.BT.ChangeLog.ChangeLogRequest_v1_0_XML.xsd"
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:q9="http://ECL.Online/">
 <soap:Body>
 <ins9:ChangeLogRequest>
 <ins9:MessageID>Valid Pricing Test</ins9:MessageID>
 <ins9:MessageDateTime>2012-04-13T10:50:55</ins9:MessageDateTime>
 <ins9:BusinessUnit>CP</ins9:BusinessUnit>
 <ins9:AccountNumber>12345678</ins9:AccountNumber>
 
 <ins9:OriginPoint></ins9:OriginPoint>
 <ins9:ReturnData>Pricing</ins9:ReturnData>
 </ins9:ChangeLogRequest>
 </soap:Body>
</soap:Envelope>

The main difference is xmlns:soap="http://www.w3.org/2003/05/soap-envelope" in Postman body and xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" in Savon. But with Savon I got Savon::HTTPError: HTTP error (405). 

My guess is if I can replace the Envelope namespace definition when Savon generating the request, this problem can be solved. Have been struggled with this for days, any help will be appreciated.
