### ISSUE TITLE
License Verification: Savon is using Socksify gem which is licensed as GPL 3.0 

### ISSUE THREAD

**Issue by abhisheknsit** [savonrb/savon#889]
# Bug report

**Current behavior:**
Savon is licensed under [MIT](https://github.com/savonrb/savon/blob/master/savon.gemspec#L18).

But [Socksify](https://github.com/astro/socksify-ruby) one of the dependencies of Savon, is licensed under [GPL 3.0](https://github.com/astro/socksify-ruby/blob/master/socksify.gemspec#L10).

If I am not wrong, having a GPL dependency, makes the parent GPL.

**Steps to reproduce current behavior:**

**Expected behavior:**

**System information:**

* ruby version: 
* savon version:

**Comment by pcai** [comment]
The fact is savon's own code is licensed under MIT, and to my knowledge is not derived from any GPL code that would compel it to be similarly licensed. Interested parties should consult relevant legal advice for their situation. Savon doesn't take any position on transitive dependency licensing issues like the one you described.
