### ISSUE TITLE
The "pretty_print_xml: true" stop working.

### ISSUE THREAD

**Issue by normanpl89** [savonrb/savon#897]
# Bug report

**Current behavior:**
Using the pretty_print_xml: true on the client definition is notprinting the request and response XML, A mount ago was working fine.

**Steps to reproduce current behavior:**
1- Create a client. 
  def client
    client = Savon.client(  wsdl: "MyURL",
                          pretty_print_xml: true,
                          raise_errors: false
    )
    return client
  end
2- Run the the program

**Expected behavior:**
The request and response XML should be displayed

**System information:**

* ruby version: 2.33

* savon version: 2

**Comment by normanpl89** [comment]
Problem fixed,

**Comment by normanpl89** [comment]
![image](https://user-images.githubusercontent.com/30607163/56770477-b19beb00-6779-11e9-851b-9584967b540c.png)

**Comment by P9GIT** [comment]
For anyone stumbling on to this page.
To make pretty print work you also have to include the "log: true" option.
