### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by Ecco** [savonrb/savon#899]
The same issue has been reported at least 2 times, and was closed by that stupid bot.

Re-creating an issue because I can't open any of the previous ones.

#820 
#895 
#862

**Comment by Ecco** [comment]
Also, correct me if I'm wrong, but #857 had the right fix for this…

**Comment by Ecco** [comment]
Seems like #469 might be related too...

**Comment by Ecco** [comment]
Also [in the forum](https://groups.google.com/forum/#!topic/savonrb/ZlBhcuyxscM)

**Comment by haider-cialfo** [comment]
@Ecco See if https://github.com/savonrb/savon/pull/905 fixes your issue

**Comment by Ecco** [comment]
> It will be closed if no further activity occurs

Not sure that's a great way to treat contributions.

**Comment by lukaso** [comment]
Given the slow pace of incorporating changes, I've created a gem that patches this issue. All you have to do is include it in your `Gemfile`:

```ruby
gem 'savon_fixes'
```

You can find the gem here: https://github.com/lukaso/savon_fixes. It currently covers off these issues and PRs: #916, #899, #820, #895, #862, #905 and #549 (they are all duplicates).

I haven't yet tested it in anger, but all tests pass, so please feedback if there are any issues. Adaptations of PRs here are also welcome.
