### ISSUE TITLE
[Question] Is it safe to re-use a client instance "for ever" in a long running process?

### ISSUE THREAD

**Issue by Hubro** [savonrb/savon#901]
Should it be safe to create one Savon client instance per thread and keep using them for ever (for example in a web server)? Or should a new client be created regularly, or for every request?

For example:

```ruby
def client
  Thread.current[:my_api_client] ||= Savon::Client.new #...
end
```

**Comment by sroller** [comment]
I actually don't know but would like to :-). Perhaps you can run some tests?
What does 'long' mean in your context?

**Comment by Hubro** [comment]
@sroller Indefinitely :)

I'm not sure how I would test it, other than assuming that it works and risking my production server.
