### ISSUE TITLE
Update of savonrb.com content

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [savonrb/savon#919]
To skip noise in #904 I am opening a separate issue concerning update of information on http://savonrb.com

As stated by @pcai,

> The maintainers no longer have control of the savonrb domain name or website content, so we are unable to update this inaccurate statement.

The `savonrb.com` domain WHOIS details contain following info:

> Updated Date: 2019-10-26T00:00:00Z
> Registrar Registration Expiration Date: 2020-03-31T00:00:00Z

So, seemingly the domain records were updated 1.5 months ago and it will expire in March
Direct contact information is protected by WHOIS privacy guarding, but there's helpful link to contact form

> Registrant Email: https://webform.meshdigital.com

Could somebody from savonrb team give it a shot and attempt establishment of communication via that avenue?

---

/cc @sos4nt @rubiii

**Comment by aleksandrs-ledovskis** [comment]
@sos4nt @rubiii

Friendly bump

**Comment by aleksandrs-ledovskis** [comment]
`savonrb.com` domain got prolonged again till "2021-03-31T00:00:00Z", so somebody out there is still keeping lights on 🤷‍♂️

**Comment by aleksandrs-ledovskis** [comment]
Not stale. The website is still unchanged/has following false statement "Savon v3 is currently under development and available for testing on GitHub. Use this version if you can handle changes and want to provide feedback"

**Comment by rubiii** [comment]
Hey. What's the problem with submitting changes to the savon/savonrb repository which hosts the website?

**Comment by pcai** [comment]
This is resolved - https://github.com/savonrb/savonrb.github.io repo now powers savonrb.com again. Thanks everyone for your help.
