### ISSUE TITLE
Wasabi URI.escape/unescape obsolete warning

### ISSUE THREAD

**Issue by pmcnano** [savonrb/savon#934]
# Bug report

**Current behavior:**
Savon requests generate obsolte warnings due to ruby 2.7 deprecation of URI.escape/unescape.

I see the issue has been fixed on Wasabi, but I don't think it's included in the latest release yet:
https://github.com/savonrb/wasabi/commit/213d70a08e698a677acd7eb21175515b126a78a8#diff-7c3adc3042c46c5df567b221e60c3442

**Steps to reproduce current behavior:**
Install on ruby 2.7
Run any savon request
Get warnings: `wasabi-3.5.0/lib/wasabi/parser.rb:90: warning: URI.escape is obsolete`

**Expected behavior:**
No warnings

**System information:**
* ruby version: 2.7.1
* savon version: 2.12.1

**Comment by olleolleolle** [comment]
The workaround until a release has been done is to use a Git dependency in your application's Gemfile. https://bundler.io/guides/git.html

**Comment by pmcnano** [comment]
Fixed my issue. Just for anyone else since I stupidly was having a hard time understanding how would that work if Savon was still not updated even in master. Just add the wasabi gem directly to your Gemfile, pulling from master. 

Thanks @olleolleolle

**Comment by olleolleolle** [comment]
The Wasabi library has had a release 3.6.0, please try that – you should be able to stop using the workaround, now.
