### ISSUE TITLE
Call throws SOAPFault "method not defined in service"

### ISSUE THREAD

**Issue by diesl** [savonrb/savon#936]
# Bug report

**Current behavior:**
I tried the usage example from the readme but get an error. I am not sure what I am doing wrong, but I hope you can point me into the right direction.

I also tried adding attributes, that are used in #646, but this still gives me the same error.

**Steps to reproduce current behavior:**

```ruby
client = Savon.client(wsdl: 'http://longisland.simple-fax.de/soap/?wsdl', log: true, pretty_print_xml: true)
# => #<Savon::Client ...>
client.operations
# => [:sendfax]
response = client.call(:sendfax, message: {
  username: '',
  password: '',
  faxnumber: '',
  data: '',
  filetype: '',
  identifier: '',
  statusurl: ''
})
```

which gives the following error:

> Savon::SOAPFault ((SOAP-ENV:Server) method "http://schemas.xmlsoap.org/soap/envelope/sendfax" not defined in service)

**Expected behavior:**

Call should be successful when using defined operation. The _sendfax_ operation was successful using a PHP test script.

**System information:**

* ruby version: 2.6.6
* savon version: 2.12.1

**Comment by olleolleolle** [comment]
Here's a runnable program, using the Bundler inline capability.

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'savon'
end

pp client = Savon.client(wsdl: 'http://longisland.simple-fax.de/soap/?wsdl', log: true, pretty_print_xml: true)

pp client.operations

response = client.call(:sendfax, attributes: { 'xmlns:tns' => 'urn:soapservice' }, message: {
  username: '',
  password: '',
  faxnumber: '',
  data: '',
  filetype: '',
  identifier: '',
  statusurl: ''
})

pp response
```

You can add version specifiers to the `  gem 'savon'` line, to attempt the program with earlier releases, to find one which works for this WSDL, thus narrowing the search space for people debugging this.

**Comment by olleolleolle** [comment]
(You could also step backwards with `wasabi` gem versions in the `gemfile` part of the above example, too.)

**Comment by diesl** [comment]
Thanks for the hints @olleolleolle!

The error disappears when I lock `wasabi` gem to 3.5.0, similar to #935.

So the question is now: Is this a bug in wasabi gem or savon gem?

**Comment by olleolleolle** [comment]
(3.6.0 introduced support for new things, which perhaps made new assumptions about structure in WSDL files, which were not universal. Please do investigate!)

**Comment by Drakula2k** [comment]
I stumbled upon a similar error: `Unable to find SOAP operation: :login Operations provided by your service: []`
I was caused by a recent newrelic gem update https://github.com/newrelic/newrelic-ruby-agent/issues/450 and was quite hard to debug.

Just leaving it here in case if anyone else will look for a solution.

**Comment by diesl** [comment]
I will close this issue in favor of #935 which covers the same bug in wasabi gem
