### ISSUE TITLE
Force Savon not to use DH

### ISSUE THREAD

**Issue by marcoschicote** [savonrb/savon#940]
Hi
When I execute

`Savon.client(wsdl: 'https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL', ssl_version: :TLSv1_2, log: true, log_level: :debug,  ssl_verify_mode: :none, soap_version: 2)`

I get 

` SSL_connect returned=1 errno=0 state=error: dh key too small (HTTPI::SSLError)`

I can reproduce this error using curl. Executing:

`curl -vvv https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL`

returns

`curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small`

However, executing 

`curl -vvv --cipher 'DEFAULT:!DH' https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL`

does not return an error. I was able to modify `openssl.conf` doing

`echo "CipherString=DEFAULT@SECLEVEL=1" >> /etc/ssl/openssl.cnf`

and this fixes the problem. However, I would like to setup Savon so that DH is not used specifically on that WS. Is that possible? Can you guide me in the right direction?

Thanks

**Comment by olleolleolle** [comment]
This would be a HTTPI gem setting, so try searching it's codebase for SSL cipher settings. (Quick guess.)

**Comment by marcoschicote** [comment]
> This would be a HTTPI gem setting, so try searching it's codebase for SSL cipher settings. (Quick guess.)

Thanks @olleolleolle. I couldn't find anything on HTTPI but found [this](https://github.com/savonrb/savon/blob/master/spec/savon/request_spec.rb#L149). Is this v3?
