### ISSUE TITLE
Wasabi::Resolver::HTTPError: Error: 500 for url

### ISSUE THREAD

**Issue by HuzaifaClustox** [savonrb/savon#958]
# Bug report

**Current behavior:**

Wasabi::Resolver::HTTPError: Error: 500 for url http://108.60.219.77:6543/BusinessServices/Billing/DiscountsAndPromotions/Shahid/Service/Service.serviceagent/ShahidPortTypeEndpoint1
/home/clustox/.rvm/gems/ruby-2.7.1/gems/wasabi-3.6.1/lib/wasabi/resolver.rb:47:in `load_from_remote'
/home/clustox/.rvm/gems/ruby-2.7.1/gems/wasabi-3.6.1/lib/wasabi/resolver.rb:35:in `resolve'
/home/clustox/.rvm/gems/ruby-2.7.1/gems/wasabi-3.6.1/lib/wasabi/document.rb:144:in `xml'
/home/clustox/.rvm/gems/ruby-2.7.1/gems/wasabi-3.6.1/lib/wasabi/document.rb:162:in `parse'
/home/clustox/.rvm/gems/ruby-2.7.1/gems/wasabi-3.6.1/lib/wasabi/document.rb:149:in `parser'
/home/clustox/.rvm/gems/ruby-2.7.1/gems/wasabi-3.6.1/lib/wasabi/document.rb:66:in `soap_actions'
/home/clustox/.rvm/gems/ruby-2.7.1/gems/savon-2.12.1/lib/savon/client.rb:28:in `operations'
/home/clustox/Desktop/Rworkplace/soapify/lib/tasks/call_wsdl_operations.rake:17:in `block (2 levels) in <main>'
/home/clustox/.rvm/gems/ruby-2.7.1/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/clustox/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
/home/clustox/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'

**Steps to reproduce current behavior:**
client = Savon.client(wsdl:"http://108.60.219.77:6543/BusinessServices/Billing/DiscountsAndPromotions/Shahid/Service/Service.serviceagent/ShahidPortTypeEndpoint1")

client.operations 

**Expected behavior:**

client.operations should return WSDL operations

**System information:**

* ruby version: 2.7.1
* savon version: 2.12.1

**Comment by DonGiulio** [comment]
I'm having the same issue, and in my case the 500 error response I get from the server is: 

      content-type of the request should be text/xml

I'm having other troubles wasabi related (i.e. doing GET calls instead of POST), I think we should switch to an older version of wasabi. looking for a suitable one

**Comment by pcai** [comment]
please reopen if you can provide additional information. @DonGiulio what content-type are you sending? @HuzaifaClustox what is the response body from the server?
