### ISSUE TITLE
Multipart Request with File Upload?

### ISSUE THREAD

**Issue by noahmatisoff** [savonrb/savon#970]
## Multipart Request with File Upload

**Motivation for this feature:**

I'm trying to integrate with an IRS SOAP API, and it expects the following request to include a "manifest" as well as an attached file that looks something like this:

<img width="643" alt="Screen Shot 2022-05-24 at 8 46 11 PM" src="https://user-images.githubusercontent.com/9292367/170175510-fcfe33bf-9759-4bd6-ba2a-535a37991142.png">

I found `savon-multipart` but it seems that's just for multipart responses. Is it possible, using Savon, to send a request like the above? Or will I need to use `Net::HTTP`?

**Proposed implementation:**

N/A

**Would this introduce a breaking change?**

No

**Are you willing to work on this yourself?**

Possibly

**Comment by pcai** [comment]
see https://github.com/savonrb/savon/commit/08f4d44e23d35d8f683cd25d53556f6f8d626feb
