### ISSUE TITLE
Decide what to do about failing softlayer_spec test

### ISSUE THREAD

**Issue by olleolleolle** [savonrb/savon#974]
# Bug report

#973 notes that one test fails.

Some digging was done into why that is. 

Find a solution that includes an explanation - we don't want to end up with a test with "a jumbled history" that happens to pass. 

The current version of the test has some superfluous code, even. 

**Current behavior:**

Test fails. Could be duplicated elsewhere. 

**Steps to reproduce current behavior:**

Run tests. 

**Expected behavior:**

No duplicated test for this behaviour. No failures.  

**System information:**

* ruby version: n/a
* savon version: current repo code

**Comment by pcai** [comment]
I believe this was fixed by https://github.com/savonrb/savon/pull/977, specifically https://github.com/savonrb/savon/pull/977/files#diff-7bdc242498659b76eb5c42f97a6fc90c6331f139cc36d3d32bbc7a7ba5dea0f5
