### ISSUE TITLE
Savon::SOAPFault - Trying to declare prefix 'xmlns'  after upgrading to 2.13.0 

### ISSUE THREAD

**Issue by OlivierGrimard** [savonrb/savon#976]
client = Savon.client(wsdl: wsdl_url, follow_redirects: true)
response = client.call(:obtener_cotizacion, message: { fecha: '2022-08-02' })

Traceback (most recent call last):
        8: from bin/console:8:in `<main>'
        7: from (irb):82
        6: from /app/vendor/bundle/ruby/2.7.0/gems/savon-2.13.0/lib/savon/client.rb:37:in `call'
        5: from /app/vendor/bundle/ruby/2.7.0/gems/savon-2.13.0/lib/savon/operation.rb:65:in `call'
        4: from /app/vendor/bundle/ruby/2.7.0/gems/savon-2.13.0/lib/savon/operation.rb:76:in `create_response'
        3: from /app/vendor/bundle/ruby/2.7.0/gems/savon-2.13.0/lib/savon/operation.rb:76:in `new'
        2: from /app/vendor/bundle/ruby/2.7.0/gems/savon-2.13.0/lib/savon/response.rb:20:in `initialize'
        1: from /app/vendor/bundle/ruby/2.7.0/gems/savon-2.13.0/lib/savon/response.rb:132:in `raise_soap_and_http_errors!'
Savon::SOAPFault ((S:Client) Couldn't create SOAP message due to exception: XML reader error: com.ctc.wstx.exc.WstxParsingException: Trying to declare prefix 'xmlns' (illegal as per NS 1.1 #4))
 at [row,col {unknown-source}]: [1,585]

See the error here:
https://stackoverflow.com/questions/73324877/savon-ruby-gem-getting-savonsoapfault-on-request/73442187#73442187

The WA is to use 2.12.1 for now.

**Comment by mpalenciano** [comment]
Same problem here with 2.13.0.
Downgraded to 2.12.1.

**Comment by yyamano** [comment]
The problem was analyzed by @cgunther. See https://github.com/savonrb/savon/pull/943#issuecomment-1213163418

**Comment by olleolleolle** [comment]
977 is now merged, please do try that change.

**Comment by mpalenciano** [comment]
Looking good for me. Thanks you.

**Comment by olleolleolle** [comment]
Very good, then this Issue is thereby closed.
