### ISSUE TITLE
Savon::SOAPFault after upgrading to >2.13

### ISSUE THREAD

**Issue by masciugo** [savonrb/savon#986]
I noticed that after switching from 2.12 to 2.13.0 (or 2.13.1) my application stop working because of some new attributes (xmlns*) added to the request envelop message. I got a Savon::SOAPFault exception.

With >2.13.1:

```
<?xml version="1.0" encoding="UTF-8"?><env:Envelope
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:tns="http://person.ws.noemalife.com/" 
xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"
xmlns="http://schemas.xmlsoap.org/wsdl/" 
xmlns:wsp="http://www.w3.org/ns/ws-policy" 
xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
<env:Body><tns:findByKeys><person><ids>
        <extension>70482983$</extension>
        <root>
          <root_oid>SAP</root_oid>
          <valid>true</valid>
        </root>
        <valid>true</valid>
      </ids></person></tns:findByKeys></env:Body></env:Envelope>
```

With 2.12.1:

```
<?xml version="1.0" encoding="UTF-8"?><env:Envelope 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:tns="http://person.ws.noemalife.com/" 
xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
<env:Body><tns:findByKeys><person><ids>
        <extension>70482983$</extension>
        <root>
          <root_oid>SAP</root_oid>
          <valid>true</valid>
        </root>
        <valid>true</valid>
      </ids></person></tns:findByKeys></env:Body></env:Envelope>
```

I also noticed that the problem is `xmlns="http://schemas.xmlsoap.org/wsdl/"`. If I replay (manually, outside Savon) the 2.13.1  request without that attribute, it works!

Can anyone help? Is it a bug? Sorry I am not so expert about SOAP protocol. Thank you

**Comment by pcai** [comment]
Hi, sorry you are running into this. This appears to be a regression from this change: https://github.com/savonrb/savon/pull/943

Based on your report I am trying to isolate if simply omitting the "xmlns" attribute addresses your problem and those reported by others. I have prepared a candidate fix here:

385964006952

Can you give this a try and report back please? You should be able to give it a try like this in your Gemfile:

`gem 'savon', github: 'savonrb/savon', ref: '3859640'`

**Comment by nathansamson** [comment]
@pcai  I've had the same issue with upgrade from 1.12.1 to 1.13.1

When I tried your fix it didn't work

The request was modified (as expected) but still didn't work ( reply was an error).
The weird thing if I copy paste this request in postman I do get the reply back I expect, so i don't understand why suddenly I get a 500 server error when using Savon... (as the request should be the exact same)

~~~
SOAP request: https://[redacted]/services/DayResultService
SOAPAction: "getCorrectedDayResults"
Content-Type: text/xml;charset=UTF-8
Content-Length: 713
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://dayResult.webservice.syntegro.be/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <env:Body>
    <tns:getCorrectedDayResults>
      <employeeSelection>101</employeeSelection>
      <dayResultGroupId>1003</dayResultGroupId>
      <startDate>2022-12-06</startDate>
      <stopDate>2023-01-05</stopDate>
      <expand>false</expand>
    </tns:getCorrectedDayResults>
  </env:Body>
</env:Envelope>

HTTPI /peer POST request to asp002.syntegro.be (net_http)
SOAP response (status 500)
vary: origin,accept-encoding
access-control-allow-credentials: true
access-control-expose-headers: AUTHENTICATION-STATUS,ID-TOKEN
content-type: text/xml;charset=utf-8
transfer-encoding: chunked
date: Tue, 06 Dec 2022 14:57:27 GMT
connection: close
server: 
<?xml version="1.0" encoding="UTF-8"?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
  <S:Body>
    <S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope">
      <faultcode>S:Client</faultcode>
      <faultstring>Couldn't create SOAP message due to exception: XML reader error: com.ctc.wstx.exc.WstxParsingException: Trying to declare prefix "xmlns" (illegal as per NS 1.1 #4)
 at [row,col {unknown-source}]: [1,451]</faultstring>
    </S:Fault>
  </S:Body>
</S:Envelope>
~~~

**Comment by pcai** [comment]
@nathansamson ok thanks for that information, but I am not sure how to proceed as the message I am receiving is that it "should" be fixed since a supposedly identical msg works in postman, but doesn't actually work in savon. Do you control the server or are you able to intercept the request? Ideally I would like to rule out "savon is sending a different body than is being logged" even though I am not sure how that would happen from my knowledge of the codebase

**Comment by nathansamson** [comment]
Yeah I fully understand your problem...

No I do not control the server, but I asked them if they can see what caused the server error on their end and what might be the reason why it does not crash with postman....

My message was more of a warning to certainly not assume your fix solves all issues

**Comment by masciugo** [comment]
> gem 'savon', github: 'savonrb/savon', ref: '3859640'

tied but:

```
[2022-12-14 10:22:51 +0100] [aad6bf36-ebfb-4e46-998a-06837a338c86] [::1] Savon::SOAPFault
[2022-12-14 10:22:51 +0100] [aad6bf36-ebfb-4e46-998a-06837a338c86] [::1] (S:Client) Couldn't create SOAP message due to exception: XML reader error: com.ctc.wstx.exc.WstxParsingException: Trying to declare prefix 'xmlns' (illegal as per NS 1.1 #4)
 at [row,col {unknown-source}]: [1,604]
[2022-12-14 10:22:51 +0100] [aad6bf36-ebfb-4e46-998a-06837a338c86] [::1] /Users/masciullo.corrado/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/savon-385964006952/lib/savon/response.rb:132:in `raise_soap_and_http_errors!'
/Users/xxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/savon-385964006952/lib/savon/response.rb:20:in `initialize'
/Users/xxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/savon-385964006952/lib/savon/operation.rb:76:in `new'
/Users/xxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/savon-385964006952/lib/savon/operation.rb:76:in `create_response'
/Users/xxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/savon-385964006952/lib/savon/operation.rb:65:in `call'
/Users/xxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/savon-385964006952/lib/savon/client.rb:37:in `call'
/Users/xxxxx/dev/cg/osr_people_gateway/lib/people_service/client.rb:61:in `block in find_by_keys'
```

**Comment by nathansamson** [comment]
Ok got it.

Savon GIT actually sends the following
"<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://dayResult.webservice.syntegro.be/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xmlns="http://schemas.xmlsoap.org/wsdl/"><env:Body><tns:getCorrectedDayResults><employeeSelection>101</employeeSelection><dayResultGroupId>1003</dayResultGroupId><startDate>2022-12-14</startDate><stopDate>2023-01-13</stopDate><expand>false</expand></tns:getCorrectedDayResults></env:Body></env:Envelope>"

Note the `xmlns:xmlns` herre which is indeed not allowed.

If I remove `pretty_print_xml: true` then I actually see the correct value but by pretty printing this illegal XML is removed from the logs.

I also added a comment in the code where I think you might have gone wrong with your previous patch

**Comment by nathansamson** [comment]
On side note 

In LogMessage we do a `Nokogiri::XML` to parse the body which seems to recover from errors (like invalid namespaces)

Should we change this behaviour to be strict?

https://nokogiri.org/tutorials/parsing_an_html_xml_document.html#parse-options

It feels like we should be pessimistic about servers trying to recover from our errors (as proven) and so ideally we should catch them as soon as possible (with possibly a more clear option). 
Also if the logging is not correct about the XML that is actually being sent is also very clearly not what anyone expects.

This could be an option to stay backwards compatible but might improve catching these types of errors earlier.

**Comment by nathansamson** [comment]
@masciugo can you give my fix a go? I had exactly same issue as you and for me my fix worked, so I suspect it also will for you

**Comment by masciugo** [comment]
@nathansamson it works. thanks a lot
I'll wait for a new release!
