### ISSUE TITLE
documentation page not working

### ISSUE THREAD

**Issue by drakon660** [savonrb/savon#993]
# Bug report

**Current behavior:**
https://www.rubydoc.info/gems/savon/Savon

404 from cloud flare

**Steps to reproduce current behavior:**

**Expected behavior:**

**System information:**

* ruby version: 
* savon version:

**Comment by olleolleolle** [comment]
Hi, the intermittent issues re: Rubydoc's web server or hosting issues we can do nothing about.

**Comment by pcai** [comment]
This looks to be back up now, closing
