### ISSUE TITLE
Compatibility Inquiry: savon 2.14.0  with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [savonrb/savon#999]
Hi,

I'm seeking confirmation regarding the compatibility of the savon 2.14.0  with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on https://github.com/savonrb/savon/blob/master/.github/workflows/ci.yml, ruby: [3.0, 3.1, 3.2, 3.3, head, truffleruby-head]. Could you please give the confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by pcai** [comment]
I don't know of any incompatibilities that were discovered in savon between ruby 3.2 -> 3.3 (at least, no one has filed anything?) so you are probably in the clear, but a savon release hasn't been cut yet since ruby 3.3 was released. I intend to get a release out soon to address this

**Comment by sydverisk** [comment]
Thanks @pcai for the update!
I look forward to the new release.
